### ISSUE TITLE
Sounds for Objective & Quest Complete

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#2397]
## Description

When you complete an objective, there should be a little happy sound (like QuestAnnounce used to do).

Whether you are in a group, or not. It's just a little positive feedback we can send the user.

https://www.curseforge.com/wow/addons/quest-announce-3

**Comment by Gogo1951** [comment]
Sounds for Objective Complete & Quest Complete

567516 - Objective Complete

558132 - Quest Complete

Pulled from https://www.curseforge.com/wow/addons/leatrix-sounds-classic -- names / IDs don't match what was on WoWHead. =P

**Comment by Gogo1951** [comment]
Mostly done except for the issue where Quest Complete doesn't always fire. (Just adding notes from last session.)

**Comment by Gogo1951** [comment]
Needs to use new event-based triggers.

**Comment by Logonz** [comment]
There seems to be 2 different camps for this issue, one that wants sounds and one that really dislike having sounds(as seen in discord (general).
People who really want the feature will look for it in settings and people who dislikes it will really dislike it.
There is a risk for an increased need for support when people will ask to turn it off because even if it is in settings some people don't look around.

The gain we get from people who wants it is in my opinion less than the amount of dislike we would get if we have it on by default, so it should in my opinion be off by default.
