### ISSUE TITLE
Revisions to Item Tracking

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#2515]
Currently we only track items in the bag of the Quester, not in the bank.

When you move items to your bag, then complete a new objective, you see a bunch of spam for every quest item you moved to your bag.

Also the tracker doesn't update when the items were spent, like if it's https://classic.wowhead.com/item=20404/encrypted-twilight-text that are used for multiple quests. The log should update on turn in, and query the bag to see what's changed and what's still available for turn in.

And we don't check if items have expired.

Also the issue where if you get an item from a "repeatable" quest it doesn't show up as obtained and doesn't fire the objective complete announce / sound.

**Comment by BreakBB** [comment]
The thing which causes the behaviour is the bad quest event system from blizzard. The API should fire events whenever something changed in the quest log. But some quests simply don't. We _can't_ know if the player has completed an objective or "not anymore" since the required items are gone, because the API does not tell us.

I am afraid there is no easy fix for this.
