### ISSUE TITLE
Screen Lag when Leave Combat during Quest 2863, Alpha Strike

### ISSUE THREAD

**Issue by protimgy** [Questie/Questie#2523]
## Bug description
During the quest Alpha Strike (quest=2863) we got extreme screen lag while in a 2-man party right when we were exiting combat (frozen screen for 1-5 seconds, it seemed to change depending on the length of combat duration somehow). Didn't occur with Questie disabled, and as expected stopped occuring once the quest was handed in. We both got a beefy pc so it might be even worse for lower end systems.

The quest is a very odd one, with it being a 'kill 5 mobs' on a 1 hour timer. not sure where the lag came from, if it only occurs in a party or not. it did occur for my party member while I disabled Questie, didn't test beyond that.

## Screenshots
n/a

## Questie version
6.2.4

**Comment by Gogo1951** [comment]
Hey @protimgy ,

I just did this quest a week or so back and I don't think the issue is related to it.

https://classic.wowhead.com/quest=2863/alpha-strike

We do have a number of issues with Questie performance at the moment. Working on fixes for Classic TBC.

The gremlins come out the longer you play to be sure. Dip in and out of a dungeon, quest for 2-3 hours straight... you find some issues. All should be sorted with a `/reloadui ` but we are also trying to address the underlying issues for Questie in TBC.

Please do update this issue if you see it across other quests.

Thanks!
