### ISSUE TITLE
Sizable donation offered: Please add button to disable display of any collection quests greater than 1 item long.

### ISSUE THREAD

**Issue by Furyswipesvg** [Questie/Questie#2543]
I will donate $100 to the team if questie gets an option to remove all collection quests (exception: 1-item quests are fine and must be listed) from being displayed.

I lead a group of multiboxers who always skip collection quests (they are torture on many boxes), and we have always wanted an addon which supports that.

**Comment by Gogo1951** [comment]
Hey mate, I sort of get why it may be OK for multiboxers not to loot things, but not sure it really fits in with what we're trying to do. Will bring it to the other devs, but gut feeling is you'd be better off with something like Limeguide to filter out quests you don't want to do. As for money, I mean... we don't really do this for the money. (= Literally any other job on earth would pay more.

Cheers!

**Comment by Furyswipesvg** [comment]
Oh, I get that. It's a near meaningless amount, but who knows, maybe if you
do this bounty, others will spring from it. Please run it by the devs--I
have been looking for this in a quest-helper for 12+ years!

**Comment by Furyswipesvg** [comment]
And hey--I'm good for the money, sucka!

**Comment by Furyswipesvg** [comment]
Not a huge fan of limewire, btw. Let's focus on questie.

**Comment by Gogo1951** [comment]
Hey man, so here's the problem... 

We can easily limit it to quests that have one drop, but it won't be quite what you want.

Some quests have only 1 drop, but it's a really rare drop. (Looking at you, Gorilla Sinew!)

So we're doing some stuff to get better data for Questie going forward. It may help. Let's talk again once we get that in place.

We may, not saying we will, but may change it up so that you can see PVP, Event, Raid, Dungeon, Kill Only... but it just gets messy, so many quests are "Kill that guy and bring he his head," or just "Bring me his head!" 

Will revisit in BC!

Cheers mate!

**Comment by Furyswipesvg** [comment]
Honestly, one rare drop, such as gorilla sinew is just something I will
have no problem putting up with--if you get it that far, I'll be
overwhelmingly happy!
But I understand. I tried looking at the lua code to see if I could fork it
and work it in, in some way--but no chance. Code is way too complex for the
script kiddie in me.
