### ISSUE TITLE
Blackmoss the Fetid - additional regular spawn point

### ISSUE THREAD

**Issue by Nerillida** [Questie/Questie#2595]
Blackmoss the Fetid Teldrassil 42.51,37.89

regularly spans at above in addition to the coords the you have marked.

**Comment by Gogo1951** [comment]
The spawn point we had was a bit of a compromise. The mob doesn't patrol all over, but he has a few spawn points. Given he's on like a 4 hour respawn timer, we didn't want to clutter the map with ! for a mob that was rarely there. Closing this, it's not perfect... but the alternative is going back to putting a fake pat in, or adding a bunch of extra ! that will confuse users when they can't find him because he's dead.
