### ISSUE TITLE
Constant errant party quest completion reports in BCC.

### ISSUE THREAD

**Issue by shooky56** [Questie/Questie#2810]

**Comment by shooky56** [comment]
My entire party had Questie-v6.3.11-TBC.zip (from Curseforge).  

One had at least partially completed "Threat of the Winterfall" (a kill quest from Winterspring).  While killing skellies in Western Plaguelands, she'd loot and we'd get a "8/8 Den Watchers complete" report.

The other (me) had loot items in my bags from repeatable quests in The Blasted Lands (jowls, pincers, etc.) and every time I'd loot skellies, Questie would report that I'd completed my loot "3/3 pincers" or something which I had in my bags already but did not loot just then.

In my case, the quest doing the errant reporting was the very first quest that showed up in my quest log.

Thank you for your efforts and hope this helps.

**Comment by meflakcannon** [comment]
This seems to happen with multiple quests. My group was running some SIlithus quests. Any time someone would Track/Untrack or mouse over a quest objective in our bags it would report the quest progress to the part chat. Effectivly rendering party chat unusable. 
Qeust we encountered it on was Abyssal Contacts, Quest ID 8361. Easy to replicate since the item to complete this is sold on the AH and is not BoP.

**Comment by drejjmit** [comment]
Turn off "``Quest Announce``" in ``Questie Options`` > ``General`` for now. 
Will be fixed for next release.
