### ISSUE TITLE
Quest 1301 Vincent Hyal error

### ISSUE THREAD

**Issue by Nerillida** [Questie/Questie#2873]
Version 6.3.13

https://tbc.wowhead.com/quest=1301/james-hyal
is a breadcrumb to
https://tbc.wowhead.com/quest=1302/james-hyal

With 1302 in the log, 1301 is not offered. correctly, by the NPC. It is not on the map, correctly. However, it is listed as available in "Quests by Zone" for Stormwind.

Database recompiled.

**Comment by drejjmit** [comment]
I completed [[35] James Hyal (1302)] and all these got correctly added to Completed.
[[35] James Hyal (1301)] (Stormwind) [[35] James Hyal (1302)] (Wetlands) [[35] They Call Him Smiling Jim (1282)] (Dustwallow)
Know that it will not be added to Quest by Zone completed unless you complete them. Just having them in quest log will not remove them from available (since you can still pick them up if you abandon the other quests exclusive to that one).
