### ISSUE TITLE
Lag (login/reload, loot roll)

### ISSUE THREAD

**Issue by bguermen** [Questie/Questie#2940]
## Bug description

1) 2s lag when loggin in and/or reloading while questie addon is active.
2) 1-2s lag when loot roll window appeares e.g. while looting in dungeon group. 

## Questie version

v6.3.15

**Comment by BreakBB** [comment]
Hey @bguermen I know the response is quite late, but as you might have read in similar tickets we need some more information from you.

Questie has a Profiler which you can start in the Advanced section of the options. Please leave it open (you can move it a bit off screen to play) and let it record especially when you are experiencing your lags. If you did record while the game lagged, share a screenshot of the profiler.

You should also make sure it really is Questie and disable all other addons. Especially the loot window is strange, because Questie does not interact with anything close to it.

**Comment by BreakBB** [comment]
Merging this with #2877 2967
