### ISSUE TITLE
Getting error messages after updating Questie a few minutes ago

### ISSUE THREAD

**Issue by cbcatanz** [Questie/Questie#2941]
I'm getting an error that states the quests I have are not in the Questie database. I have uninstalled and reinstalled the addon using WoWUp. I have uninstalled and installed the addon manually. Also, I have tried resetting the addon in game under the Advance tab but I'm getting the same error messages.

**Comment by drejjmit** [comment]
That's because you have TBC quests in your quest log while running Classic Era version.
Install TBC version and go to ``Questie Options`` > ``Advanced`` > ``Reset Questie``
If you're using ``WowUp``, make sure to install latest version and it will grab TBC version for you, then restart Wow and ``Reset Questie``

**Comment by cbcatanz** [comment]
That did not work.
