### ISSUE TITLE
Onu is Meditating (961)

### ISSUE THREAD

**Issue by Nerillida** [Questie/Questie#3035]
Version 6.4.1

For information. I am unsure if you handle this

The quest Onu is Meditating (961) is only available "inside" quests return to nu 950 and The Master's Glaive (944) i.e when either of those quests are in the log. Its purpose is to replace a Phial of Scrying. It is never returned as completed.

**Comment by drejjmit** [comment]
It will be flagged as complete when you complete ``The Master's Glaive (944)``
Did you have any issues with the quest?
![image](https://user-images.githubusercontent.com/15526476/126340647-1864ca0c-bcc2-42d5-9341-56b411b74fbc.png)

**Comment by Nerillida** [comment]
No problem. I had researched it for another. Technically, it should be after Return to Onu (950) is turned in as it is still available up to that point. But, <shrug>, I don't suppose it matters that much.

**Comment by drejjmit** [comment]
You are correct. It will be set as completed after **Return to Onu (950)**. 
```
        [961] = {
            [questKeys.preQuestSingle] = {944},
            [questKeys.exclusiveTo] = {950},
        },
```
> There are more than a few = only active while another is in the log. But I would suppose that you're aware of that.

Yes. They are tagged as **parentQuest** in the database. But because this quest is open during more than one quest this is the only way we can do it.

So i guess everything is fine then. Just reopen if there are still issues.
