### ISSUE TITLE
Midsummer event quests don't display on maps properly

### ISSUE THREAD

**Issue by Jokaleth** [Questie/Questie#3058]
Midsummer event quests are shown on the minimap

![image](https://user-images.githubusercontent.com/87456827/126855326-f98d6763-76ee-4089-a162-6683df325602.png)

But not on the full map

![image](https://user-images.githubusercontent.com/87456827/126855339-8ae43bb1-6aee-4829-ad65-197f1236d664.png)

Despite the option for "Enable Event Quest Icons" being set to Off.

**Comment by FortSanJacinto** [comment]
this is still happening
![minimap](https://user-images.githubusercontent.com/54084551/127387111-d2c62ae1-490c-4925-a45e-63c5eb6bdce3.PNG)
![map](https://user-images.githubusercontent.com/54084551/127387132-919296a2-8729-416d-8746-becce72b6749.PNG)

**Comment by BreakBB** [comment]
@FortSanJacinto With TBC the default Blizzard UI now shows minimap icons.

The problem is, that Blizzard released a different version of the Midsummer event than it was in Classic and we were not prepared for it. The quests are now already fixed, but the fixed version is not released yet. It will follow soon.

Merging this issue with #3055
