### ISSUE TITLE
Drop down menus still missing from the map

### ISSUE THREAD

**Issue by Trakker23** [Questie/Questie#3221]
Questie-v6.6.4-tbc

Since v6.6.0 the maps have been missing the drop down menus to change location. 

Can we at least bring back the old versions on Cursed forge to downgrade to?
![Capture](https://user-images.githubusercontent.com/93481329/139590305-4d97a552-2064-4e9f-9332-f6afd1a48d84.PNG)
Missing drop downs.

![Capture2](https://user-images.githubusercontent.com/93481329/139590321-c23c7d65-90ac-4dc0-a5cc-36d51d7f7f98.PNG)
Drop downs showing again with questie unloaded.

**Comment by BreakBB** [comment]
Hey @Trakker23

this is intentional behaviour, because Blizzard has some nasty UI bugs in their default UI which breaks many addons. Till those are fixed or we find a better work around the drop down will stay hidden.

If you want to downgrade to another Questie version you can always do so if you look at the "Files" tab on Curseforge. Make sure to recompile your database after you do so (`/questie` -> Advanced -> Recompile Database).

**Comment by Trakker23** [comment]
The versions of Questie on Curseforge only goes back to v.6.6.0. Which was the first version the drop down menus were removed. All the previous have been removed when this recent version went in. Do we have a download location for v6.5.1?

**Comment by BreakBB** [comment]
@Trakker23 check the website. All versions are still there https://www.curseforge.com/wow/addons/questie/files/all

**Comment by Trakker23** [comment]
Thank you.
