### ISSUE TITLE
Questie fails to load

### ISSUE THREAD

**Issue by Keaweone** [Questie/Questie#3222]
## Bug description
I encountered the first error upon entering the game and Questie tried to load. Any time I try to do anything with Questie I get a new error. It does not appear on screen and if I try to recenter it in the hopes of making it appear I get another error. All these errors began with the latest update.

## Screenshots
See attached.

## Questie version
6.6.4

![WoWScrnShot_103121_221010](https://user-images.githubusercontent.com/93499935/139612700-e80d5f14-e096-4c72-8aac-940f21f486b4.jpg)

**Comment by Laumesis** [comment]
We got report of this via Discord earlier. It is a new bug in latest Questie version, which will be fixed in next release. Sorry for inconvenience caused.

You can solve issue by completing boosted character start quests.
Or possibly by disabling sorting of quests in Questie Tracker, see the screenshot below.
Third possible option is disable Questie Tracker.

You may revert settings back to original once you have completed boosted character start quests.

![image](https://user-images.githubusercontent.com/75958501/139654439-7cad2e13-bb7e-4e95-a50d-7aa838dfd9a2.png)

**Comment by Laumesis** [comment]
For developers: The buggy commit is 3260d28661d74be617f56c086db1c27986656677

**Comment by Keaweone** [comment]
Thank you, that worked for me.
