### ISSUE TITLE
QuestieCorrections.lua:161: attempt to index field 'itemData' (a nil value)

### ISSUE THREAD

**Issue by WypukT** [Questie/Questie#3250]
## Screenshots
![Screenshot 2021-11-16 050159](https://user-images.githubusercontent.com/94421893/141888165-878e8347-6903-45b4-aca0-b71f02e404ae.png)

## Questie version 6.7.0

delete addon, clear WTF - install again but always this error, how fix this?
WoW version 1.14.1

addon v6.6.4 work normaly

**Comment by WypukT** [comment]
reinstall addon, clear WTF - always this error, how fix this?

**Comment by WypukT** [comment]
> 
> ## Bug description
> ## Screenshots
> ## Questie version

**Comment by BreakBB** [comment]
Hey @WypukT

are you sure you are installing Questie to the correct folder? You can navigate to the correct folder using the Battle.net client

![grafik](https://user-images.githubusercontent.com/33514570/141940889-334c543a-ac3f-4b94-970e-99bee09af8f7.png)

**Comment by WypukT** [comment]
> 
> 
> Hey @WypukT
> 
> are you sure you are installing Questie to the correct folder? You can navigate to the correct folder using the Battle.net client
> 
> ![grafik](https://user-images.githubusercontent.com/33514570/141940889-334c543a-ac3f-4b94-970e-99bee09af8f7.png)

addon v6.6.4 work normaly...

**Comment by drejjmit** [comment]
Try deleting Questie from your AddOns folder and install/update it again.

**Comment by WypukT** [comment]
> 
> ## Bug description
> ## Screenshots
> 
> ![Screenshot 2021-11-16 050159](https://user-images.githubusercontent.com/94421893/141888165-878e8347-6903-45b4-aca0-b71f02e404ae.png)
> ## Questie version 6.7.0
> 
> delete addon, clear WTF - install again but always this error, how fix this? WoW version 1.14.1
> 
> addon v6.6.4 work normaly



> 
> 
> Try deleting Questie from your AddOns folder and install/update it again.

**Comment by BreakBB** [comment]
The past showed this issue is related to a corrupted installation of Questie and not something we can fix on our side.

Since you said v6.6.4 works fine (I assume you extracted the ZIP in the same folder) some configuration value seems to interveine here. Did you delete the WTF folder while WoW was closed? For Questie it also is enough if you just search your WTF folder for these two files and delete them:

`Questie.lua` and `Questie.lua.bak`

It might also be helpful if you share a screenshot of the folder path your addon/Questie folder. As Drejjmit said: It really is important, that you delete the Questie folder and not just paste the new files into the existing Questie folder. Also make sure to have WoW closed while changing/deleting files in the WoW installation folder.

**Comment by WypukT** [comment]
close game, delete folder Questie, delete folder WTF, install addon = have error...
close game, delete folder Questie, delete Questie.lua and Questie.lua.bak in WTF folder, install addon = have error...

**Comment by BreakBB** [comment]
@WypukT did you try to disable all addons except Questie?

**Comment by Laumesis** [comment]
@WypukT you are trying to use TBC version of the addon on v1.14.x client. Try remove your current Questie folder under addons and install Era version of the Addon

**Comment by BreakBB** [comment]
I assume this was an installation error. If this is still an issue feel free to open up a new issue.
