### ISSUE TITLE
A Rogue's Deal not completing

### ISSUE THREAD

**Issue by bkuhns-git** [Questie/Questie#3270]
Accepted and did the quest 'A Rogue's Deal' and the exclamation marker for accepting the quest remained on the map/minimap. Probably doesn't register because the quest is weird and it takes a second to accept (mark him hostile) and complete (wait for him to eat and be full health). -bk

**Comment by BreakBB** [comment]
Hey @bkuhns-git 

Can you do a `/reload` and check if the mark is still shown on the map?

If yes it would be great if you could enable "Show Quest IDs" in the Advanced Options and share a screenshot of it.

If the mark is not shown anymore than it was a simple "desync" which is caused by some fuzzy Questie logic which we are currently rebuilding (PR #3111)
