### ISSUE TITLE
Questie is missing <Reagent Vendor> from the townsfolk tracker.

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#3297]
## Bug description

Questie is missing Reagents Vendors from the townsfolk tracker.

## Screenshots

![image](https://user-images.githubusercontent.com/55365231/147854435-bfafbd3c-7888-4cde-8d1b-bca8040c974d.png)

Here's the list you verify data from. Check the "Sold By" tab for Reagent Vendors.

https://tbc.wowhead.com/item=17028/holy-candle

https://classic.wowhead.com/item=17028/holy-candle

## Questie & WoW version

Latest, playing SoM.

**Comment by Gogo1951** [comment]
Missing from TBC too.

![image](https://user-images.githubusercontent.com/55365231/147854733-ef86d9db-f619-4d46-80a4-f2a218bfbb53.png)

**Comment by Gogo1951** [comment]
Also interesting that TBC has the Stable Master, but Classic doesn't.

**Comment by BreakBB** [comment]
Hey @Gogo1951 

on what class did you experience this?

"Reagents" is showing up for me on my Mage and Druid (as they can use a reagent), but not on my Warrior (since a Warrior does not need any reagent). This in on purpose, for now. But I think we should change it to show up for everyone so one can bring alone some reagents for someone else.
"Stable Master" and "Pet Food" only shows up for Hunters (did you check SoM and TBC both on a Hunter?).

Also did you try to recompile the database?

`/questie` -> "Advanced" tab -> Recompile Database

**Comment by Gogo1951** [comment]
Didn't realize Reagent Tracker was specific to Class. Doesn't show on Warrior or Hunter... because they have no "reagents." Thanks!
