### ISSUE TITLE
drop menus world map

### ISSUE THREAD

**Issue by kalebm90s** [Questie/Questie#3406]
i see the message when logging in regarding the blizzard IU issue, just curious if theres a temporary fix known, or another option for questing lol , sadly enough i am a bit lost without your addon. xD always my first thought when i think what addons to use, however it started a day or so ago, and i saw no inquires since 2 days ago idk if anyone else has asked, sorry if so, hope to have yall back soon! thanks

**Comment by kalebm90s** [comment]
ok so, unsure if i turned it off the other day by mistake or something caused it to, but i used a button in the top right corner of world map to turn questie on and see the quest drops on world map.. sorry.

**Comment by BreakBB** [comment]
Hey @kalebm90s not sure if I understand you correctly. But the drop downs are hidden on purpose by Questie to reduce the general issues of so called "taints" which break most parts of the UI. The "taints" we are preventing this way are caused by the Blizzard UI itself, so there is not much we can do on our side except for waiting for a proper fix on Blizzards side.

Personally I never used these drop downs so I don't see a problem when not using them. On the other hand I am also using [Leatrix Maps](https://www.curseforge.com/wow/addons/leatrix-maps-bcc) as full world map overhaul which helps a lot.

**Comment by BreakBB** [comment]
Merging this with #3277
