### ISSUE TITLE
Objective locations missing for "Seeds of the Blacksouled Keepers"

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#3765]
## Wowhead link

https://www.wowhead.com/wotlk/quest=11319/seeds-of-the-blacksouled-keepers

**Comment by Yttrium-tYcLief** [comment]
This quest objective is pointing at [NPC #24235](https://www.wowhead.com/wotlk/npc=24235/cyclothar) but actually needs to be pointing at [NPC #23876](https://www.wowhead.com/wotlk/npc=23876/spore).
This is an error in Blizzard's quest objective data, and not the fault of Wowhead or Questie, but considering this bug has existed for so long, it might as well be fixed in the latter.
