### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by richaj85** [Questie/Questie#3868]
Seeing this with the latest version:

[QuestieQuest]: v6.13.2 - There was an error populating objectives for Pride of the Fel Horde 9496 3 No error
[06:11:37] Interface\AddOns\Questie\Modules\Map\QuestieMap.lua:557: No UiMapID or fitting parentAreaId for areaId : 3535 - Warchief Kargath Bladefist
[06:11:37] [string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:951: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:949>
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\Questie\Modules\Map\QuestieMap.lua"]:557: in function `DrawWorldIcon'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:889: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:836>
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:701: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:646>
[string "=[C]"]: in function `xpcall'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:949: in function <...erface\AddOns\Questie\Modules\Quest\QuestieQuest.lua:947>
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:1004: in function `PopulateObjectiveNotes'
[string "@Interface\AddOns\Questie\Modules\Quest\QuestieQuest.lua"]:502: in function `GetAllQuestIds'
[string "@Interface\AddOns\Questie\Modules\QuestieInit.lua"]:242: in function <Interface\AddOns\Questie\Modules\QuestieInit.lua:162>
[06:11:37] Questie: [ERROR] [QuestieQuest]: v6.13.2 - There was an error populating objectives for The Will of the Warchief 9495 1 No error

**Comment by BreakBB** [comment]
Hey @richaj85 it seems you are also using wowup and got the Wrath-beta version instead of the stable version for TBC.

Can you delete your Questie folder and install this version manually? https://github.com/Questie/Questie/releases/download/v6.13.2/Questie-v6.13.2.zip

We are already in contact with wowup to sort that issue out.

**Comment by Raina1007** [comment]
hey @richaj85 I'm a mod for the WowUp Team, would it be possible to hop into our discord so we can figure out how you ended up with the wrong version of questie? You can use this link to join our discord if you aren't part of it already. https://discord.gg/aewPPjnJQ5

**Comment by richaj85** [comment]
Hi,

Would not be able to do that until after 5 pm CT.

But, I was just using WoWUp normally and saw it offered an update for
Questie. I let it update the mod.

[image: image.png]

**Comment by Raina1007** [comment]
@richaj85  That's why, no rush. Yeah, it seems to be a weird issue that we are working on. We did have another person provide the info we need and I've figured out a work around that should fix your issue. So when you can join WowUp's discord and you can ping me in the help me channel and I'll walk you through what to do. :-)
