### ISSUE TITLE
Tracker re-enables on login

### ISSUE THREAD

**Issue by mcfarlin72** [Questie/Questie#3887]
Tracker gets disabled thru the in-game options menu. When I logout and back in, it is re-enabled.

**Comment by BreakBB** [comment]
Hey @mcfarlin72 I bet you are using wowup and are on TBC/SoM/Era, right? There was a problem with wowup and the Questie beta release for Wotlk. Instead of shipping the stable v6.13.2 to TBC/SoM/Era the Wotlk-beta versiono was sent which is a problem in some places.

You should remove the Questie folder and install this version: https://github.com/Questie/Questie/releases/download/v6.13.2/Questie-v6.13.2.zip

I will look into this issue nevertheless to see if it is an issue on Wotlk as well 👍🏻
