### ISSUE TITLE
retail 

### ISSUE THREAD

**Issue by Imna1975** [Questie/Questie#3951]
One question would you also do a retail version?

**Comment by BreakBB** [comment]
Hey @Imna1975 

no there is no retail version of Questie and most likely will never be, sorry. Most people are using Questie for the improved questing system, but retail already has one that is even better than the one Questie gives the player.

Moreover we are really just a few people with very limited time so it won't be easy to support yet another Client version 🙈

**Comment by xenoterracide** [comment]
I mean, I also use questie to find out where vendors are, available quests are... even if some things are better on retail, it's not all. :'(

**Comment by tyestor** [comment]
I emphatically disagree that retail's:

1. Objective frame is better than Questie's.
2. Objective tracking is better than Questie's.

Retail has a few Quest addons available: Wholly, BTWQuests, and AllTheThings. ATT isn't even specifically a Quest addon (it's also clunky and butt ugly) and the other two kind of suck. Questie is neat and clean and integrates marvellously with the base UI and even UI overhauls like ElvUI. Questie is also a better objective tracker than both Kaliel's Tracker and Syling Tracker.

With one blow Questie would replace at least 5 AddOns (I am sure that the Questie dev team would completely own world quests too).

**Comment by BreakBB** [comment]
Thanks for your kind word @tyestor and chiming in on this.

The biggest issue by far is: The Questie team is really small and since release of Cata, we didn't even polish all the data of that expansion. Thinking about handling three times the amount of data is giving us nightmares.

So as long as the team not miraculously doubles, retail support is not even in near sight.
