### ISSUE TITLE
Build not working without fetched Tags

### ISSUE THREAD

**Issue by hugelol** [Questie/Questie#3954]
Hello everyone,

i tried to build Questie yesteday from my forked repo, failed all the time. 
Dug a bit into it, problem was i forked Questie to my repo without the tags. 

![grafik](https://user-images.githubusercontent.com/57292028/185502876-cdf41a54-c6d9-4090-a8e0-d363239b0600.png)

There should be a new arg for ignoring tags (exlude part of build.py) or using a "test-build-dummy-Tag"-Number.

**Comment by BreakBB** [comment]
Hey @hugelol if you just want to test your changes there is no need to run the build script. Just move the entire folder to your addons folder and you are good to go (just like you would install Questie).

The build script is only for building release ready ZIPs which don't include irrelevant files.

Or is there something specific you want to do?

**Comment by hugelol** [comment]
Never thought about this. Than my point is, of course, absolutly irrelevant.

**Comment by Muehe** [comment]
Just to expand the bit on the actual problem, I assume by "forked without the tags" you mean you downloaded the repo instead of cloning it with git? The error

> returned non-zero exit status: 128.

means the directory you are operating in is not a git repository (i.e. no `.git` sub-directory is present or its content is malformed), and that's exactly what happens when you use the download button on GitHub. If you instead open a shell in the AddOns directory (or wherever you want to place Questie) and do `git clone https://github.com/Questie/Questie.git` the script should work.

Also small FYI, when you make changes to Questie you will sometimes have to use the "Recompile Database" button in the advanced options before they take effect, specifically for additions to the corrections files.
