### ISSUE TITLE
Adjusting the font size causes the tracking box to continuously move to the left

### ISSUE THREAD

**Issue by SwimmingTiger** [Questie/Questie#4015]
## Bug description

1. Set game text to Simplified Chinese (`SET textLocale "zhCN"`).
2. Adjust any font size of the tracking box.
3. The tracking box will move to the left unexpectedly.

Note: Chinese characters are about twice as wide as the Latin alphabet. And in UTF-8 each Chinese character occupies 2-4 bytes.

The same phenomenon can be observed in English locale if you adjust the `Font Size for Objectives` (See [#issuecomment-1235471206](#issuecomment-1235471206)).

## Screenshots

Animated Gif:

![questie](https://user-images.githubusercontent.com/4986069/188144027-ba9beba1-860b-4a6a-a050-2e5a56d8e301.gif)

## Questie & WoW version

* Questie: 7.0.1
* Wow: 3.4.0

**Comment by SwimmingTiger** [comment]
The same phenomenon can be observed in English locale if you adjust the `Font Size for Objectives`.

Animated Gif:

![questie](https://user-images.githubusercontent.com/4986069/188150099-0cda2e23-96b9-4dcd-a46e-df730e1638ee.gif)

**Comment by BreakBB** [comment]
Hey @SwimmingTiger this is a really great report. Thanks a lot for it!

We will take a look into it 👍🏻

**Comment by Iznogud91** [comment]
Just to add to this, cause it maybe goes hand in hand with it...
My tracker moves the same way, but it does so everytime something updates on the quest tracker (like questprogress or finished quest).

**Comment by BreakBB** [comment]
Are you also on Questie v7.0.1 @Iznogud91 ?

**Comment by Iznogud91** [comment]
@BreakBB yes

**Comment by SwimmingTiger** [comment]
> Just to add to this, cause it maybe goes hand in hand with it... My tracker moves the same way, but it does so everytime something updates on the quest tracker (like questprogress or finished quest).

Yes I have the same problem, but it's hard to reproduce. Sometimes an update doesn't cause the frame to move. But eventually, after a while, the frame will deviate significantly from its original position, even if I don't adjust the font size.

**Comment by CursedShadow** [comment]
This issue persists on Questie version 7.0.4.

And to add to the symptoms already mentioned here, the tracker demonstrates this behavior when minimizing and opening it. Spamming that will also rapidly move it to the left across my screen and as seen below:

https://gfycat.com/ReasonableColorlessDragonfly

It appears that whatever is the issue, it's causing the size of tracker to expand horizontally rather than the position of the tracker changing. Seems to ignore the fact that position and size are locked. 

Only way to temporarily fix this is to reload the UI and it will reset back to its normal size until it decides to slowly stretch its way across my screen again due to whatever is causing it.

**Comment by BreakBB** [comment]
Hey @CursedShadow could you try to manually set the Tracker size (CTRL + Leftclick in the lower right corner) and see if that helps?

**Comment by CursedShadow** [comment]
> Hey @CursedShadow could you try to manually set the Tracker size (CTRL + Leftclick in the lower right corner) and see if that helps?

Curiously it no longer shuffles left by itself after doing that. 

But now instead of collapsing/minimizing to where the header is, it collapses to the middle of the tracker. It does expand to the left if I move the lower right corner to the right off the screen. 

Unsure if that's intended behavior?

https://gfycat.com/WeeEmbellishedAppaloosa

**Comment by BreakBB** [comment]
Thanks for testing, that gives us a hint at least about where to look.

Hmmm... I am unsure if the collapsing is/was intended or not 😅 But I agree that it does look strange and should behave like before.
