### ISSUE TITLE
Tracker SetPoint Broken

### ISSUE THREAD

**Issue by aristoblis** [Questie/Questie#4076]
Hi.  I am experiencing an issue where no matter what I set the Tracker SetPoint to in the config, the tracker acts like the setpoint is bottom left.  It grows from bottom up, and quests fill in from bottom to top, left to right.  Is this an issue anyone else is having or it is just me?

**Comment by jer-tremb** [comment]
I have been seeing the same thing too.

The tracker setpoint simply stopped working. Not sure why. I want  it to grow right to left, top to bottom (Top Right) and that simply stopped working yesterday.

Another thing I noticed at the same time, the tracker can no longer grow offscreen, I'm pretty sure this used to occur but not the edge of the screen seems to stop the tracker from growing, and instead, it pushes the tracker to grow upwards.

**Comment by jerbookins** [comment]
The issue I have seen is that it behaves the same, no matter which Tracker SetPoint setting I choose. There is no functional anchor point.

The expected behavior for Top is that the tracker quest list grows downwards, leaving the top side of the frame locked in place.
The expected behavior for Bottom is that the tracker quest list grows upwards, leaving the Bottom side of the frame locked in place.

Neither of these is true.

**Comment by BreakBB** [comment]
Hey 👋🏻 

Yeah this is a know issue. You might wanna give the beta version [linked here](https://github.com/Questie/Questie/issues/3987#issuecomment-1241038185) a try and see if that fixes/changes your issue.

We know the Tracker is in quite a wonky state since the pre patch, we are working on it 🙈

**Comment by BreakBB** [comment]
A late update on this: The Tracker SetPoint option currently does nothing really. The rework required for the Tracker to work with Wotlk stripped many functions of the Tracker got disabled to focus on a first "working" solution.

There are many things we have yet to add back to the Tracker.
