### ISSUE TITLE
Error When Getting First Quest

### ISSUE THREAD

**Issue by Comicus** [Questie/Questie#4152]
## Bug description

It seems to happen when I first log in and mouse accepting first quest or targeting a quest I already have

## Screenshots

6x Questie\Modules\Map\QuestieMap.lua:836: bad argument #1 to 'next' (table expected, got nil)
[string "=[C]"]: in function `next'
[string "@Questie\Modules\Map\QuestieMap.lua"]:836: in function `GetNearestSpawn'
[string "@Questie\Modules\Map\QuestieMap.lua"]:924: in function `GetNearestQuestSpawn'
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:1587: in function <...ceQuestie\Modules\Tracker\QuestieTracker.lua:1572>
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:848: in function <...ceQuestie\Modules\Tracker\QuestieTracker.lua:758>
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:913: in function `Update'
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:1541: in function `func'
[string "@Questie\Modules\Libs\QuestieCombatQueue.lua"]:25: in function <...eQuestie\Modules\Libs\QuestieCombatQueue.lua:17>
[string "@SharedXML\C_TimerAugment.lua"]:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"

## Questie & WoW version

TBC > Wrath

**Comment by BreakBB** [comment]
Hey @Comicus sorry for the late response on this. Wotlk launch still is pretty stressful for us 🙈 

Is this still an issue for you? If yes, could you share all quests you know you have in your quest log since this error happens?

**Comment by cralor** [comment]
This has been an issue for me since the expansion release.

`12x Questie\Modules\Map\QuestieMap.lua:839: bad argument #1 to 'next' (table expected, got nil)
[string "=[C]"]: in function `next'
[string "@Questie\Modules\Map\QuestieMap.lua"]:839: in function `GetNearestSpawn'
[string "@Questie\Modules\Map\QuestieMap.lua"]:927: in function `GetNearestQuestSpawn'
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:1385: in function <...ceQuestie\Modules\Tracker\QuestieTracker.lua:1370>
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:658: in function <...ceQuestie\Modules\Tracker\QuestieTracker.lua:568>
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:732: in function `Update'
[string "@Questie\Modules\Tracker\QuestieTracker.lua"]:1339: in function `func'
[string "@Questie\Modules\Libs\QuestieCombatQueue.lua"]:25: in function <...eQuestie\Modules\Libs\QuestieCombatQueue.lua:17>
[string "@SharedXML\C_TimerAugment.lua"]:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
`

**Comment by BreakBB** [comment]
@cralor @Comicus I guess you are both using "By Proximity" sorting of the Tracker objectives? When switching to the default "By Zone" sorting should work around the issue for now.

Tracker improvements/fixes are on our list. But all team members are currently trying to fix as many quests as possible.

**Comment by cralor** [comment]
Makes a lot of sense. Thanks.
________________________________

**Comment by Comicus** [comment]
I do use Proximity...  thank you very much for the input, I will use zone for now... Look forward to Questie and your staff for all you do for us...
