### ISSUE TITLE
Duplicated quests

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#4176]
## Screenshots

![grafik](https://user-images.githubusercontent.com/33514570/192389067-ac3ed936-8810-4f84-b157-24307ac1a74f.png)

## Questie & WoW version

v7.2.1

**Comment by Yttrium-tYcLief** [comment]
For the first one, from a 2008-era comment on Wowhead: "There are two versions of this quest, with different completion texts. The first one has Garrosh spitting in disgust at your evident fear. This one, in which he is kinder to you, happens if you have completed the Greatmother questline in Nagrand."

We may need to figure out which quest is the actual threshold for determining which quest you get.

**Comment by BreakBB** [comment]
These are not even available ingame
![grafik](https://user-images.githubusercontent.com/33514570/192553933-4477c5a1-9577-472b-b1f3-cd5fe884ab71.png)

**Comment by BreakBB** [comment]
For "Hellscream's Vigil" - 11586 was available on my character
