### ISSUE TITLE
Large amount of quests in howling fjord not showing up on the map

### ISSUE THREAD

**Issue by Kado201** [Questie/Questie#4194]
I've tried to reinstall, through curseforge and manually, disabled all other addons, updated all other ui addons and it still isn't showing a large amount of quests. Seems other people are having the same problem including people in my guild. Hope you guys can fix it soon!

**Comment by aanttila** [comment]
Current quests I can't see on the map:
- Apply Heat and Stir
- Brains! Brains! Brains!
- Skorn Must Fall!
- The Cleansing

**Comment by Yttrium-tYcLief** [comment]
To clarify, what do you mean by "not showing up on the map" - are you referring to their objective icons (go kill X mob located here) or the actual pickup icons (yellow exclamation point)?

Additionally is this Horde or Alliance-side?

**Comment by nerolite** [comment]
I can answer based on my own experience with these non-visible quests: The objective icons. Horde side.

**Comment by Yttrium-tYcLief** [comment]
Okay, with objective icons a large number of these are fixed in #4186 which should be included in a new version soon. I haven't fixed all of them, but am actively working on the rest. I know for instance that I've definitely fixed Brains! x3 already.

**Comment by Yttrium-tYcLief** [comment]
If you guys can provide a list of the ones having issues, that'd be immensely helpful. Otherwise I just fix them as I encounter them when levelling ingame.

**Comment by nerolite** [comment]
I have observed the following quests missing objective icons:
- Rivenwood Captives
- Skorn Must Fall
- Draconis Gastritis
- March of the Giants
- Apply Heat and Stir (1)
- Field Test (1)

(1) Same quest chain

Thanks for looking into this!

**Comment by Yttrium-tYcLief** [comment]
Okay, I've fixed a majority of those already but it's good to have a definite list for the others. Will work on them shortly.

**Comment by Yttrium-tYcLief** [comment]
> The Cleansing

This one actually works already, but the quest is a little misleading. You have to go to the top of the mountain at the very edge of the map. The quest marker is much more obvious when looking at Grizzly Hills instead of Howling Fjord, even though it's technically a Howling Fjord quest and within the bounds of the zone.

**Comment by Yttrium-tYcLief** [comment]
> The Cleansing

@aanttila This one actually works already, but the quest is a little misleading. You have to go to the top of the mountain at the very edge of the map. The quest marker is much more obvious when looking at Grizzly Hills instead of Howling Fjord, even though it's technically a Howling Fjord quest and within the bounds of the zone.
