### ISSUE TITLE
Cant track quests when you must use quest item

### ISSUE THREAD

**Issue by Gazz15** [Questie/Questie#4227]
Hi questie cant track quests when you must use quest item.. its so frustrating.. can you resolve that? thx

**Comment by PhoenixXYZ** [comment]
Think he means most quests where there is a item you must use dont have anything showing where it is etc on the map

**Comment by Yttrium-tYcLief** [comment]
> Think he means most quests where there is a item you must use dont have anything showing where it is etc on the map

If that's the issue at hand, yes a lot of WotLK quests have broken objective data right now. We're working on it, but each one has to be fixed one at a time, manually, and it's not a simple process.

**Comment by Dyaxler** [comment]
I think he's referring to Quests that require an item to use while completing the quest. If an item is "given" by the quest giver then a button appears in Questie next to said quest. But if an item is dropped by a mob and that drop is the "Quest Item" it doesn't appear in Questie. This has been fixed in: [Pull Request](https://github.com/Questie/Questie/pull/4664).
