### ISSUE TITLE
30% work rate...

### ISSUE THREAD

**Issue by Wotlkhype** [Questie/Questie#4264]
![WoWScrnShot_093022_125247](https://user-images.githubusercontent.com/114745228/193268975-87fb619f-ab27-4131-bb21-4bb3d3f34c4a.jpg)

As you can see. 9 quests in Icecrown, questie shows where to go for 3 of them... this has been a consistent issue for majority of quests.

**Comment by BreakBB** [comment]
It's been worked on and we are aware of quest issues. Icecrown is especially bad, since there are more "complex" quests then elsewere.

Check wowhead for now or actually read the quest text and please give us some time to get the fixes in @Wotlkhype .

As you can see by the update rate, we are heavily working on quest fixes in the last days even though we also want to play the game.
