### ISSUE TITLE
Hour of the Worg has weird turn in path

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4300]
![image](https://user-images.githubusercontent.com/55365231/193431797-df537c25-c5a3-46f9-b61e-ef40172b08e6.png)

**Comment by Yttrium-tYcLief** [comment]
I saw this one myself and was wondering at the time what was up, but I just remembered that I did that one last night. Judging by the locations of the bends there, I think it's a data error where the NPC's possible locations (she exists at Oneqwah but also gets spawned on Bloodmoon during the quest) are being read as a path, rather than just possible locations. Will look into it, should be an easy fix.
