### ISSUE TITLE
Several WotLK breadcrumb quests showing incorrectly as available.

### ISSUE THREAD

**Issue by Paah** [Questie/Questie#4340]
[72] Travel to Moa'ki Harbor (both IDs 12117 and 12118)
- Completing [72] Let Nothing Go To Waste (ID 11958) locks both of the above quests.

[77] Lakeside Landing (ID 12651)
- Completing [76] The Part-time Hunter (ID 12654) locks the above quest.

[72] Of Traitors and Treason (ID 12171)
- Completing [72]  Naxxramas and the Fall of Wintergarde (ID 12235) locks the above quest and its followup 12174. Interestingly I was able to pick up and complete the first quest (The Lost Courier, 12157) even afterwards, but the 2nd and 3rd step of the chain remained unavailable. (12235 being the fourth).

[75] Close Call (ID 12638)
- The Drakuru questline in Zul'Drak seems to have 2 different starting lines, either 12631 -> 12637 -> 12629 or 12633 -> 12638 -> 12629, depending on whether you did the Drak'Tharon Keep dungeon quest 12238 beforehand. I did not do the dungeon and completed the former of the starting lines in Zul'Drak. Questie is incorrectly showing Close Call as available for me.

**Comment by Yttrium-tYcLief** [comment]
Lakeside Landing already fixed and included in a version soon - can anyone confirm the others, maybe with citations from older Wowhead comments?

Breadcrumb lockouts and pre-reqs are often prone to misinformation since their exact mechanics are pretty nuanced, so having some confirmations of what *exactly* happens would give me a lot more confidence before implementing those changes.

**Comment by Keador** [comment]
[72] Travel to Moa'ki Harbor (both IDs 12117 and 12118) still showing for me
