### ISSUE TITLE
Dungeon Quests Don't Show Up Right

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4374]
Few issues...

![image](https://user-images.githubusercontent.com/55365231/194733335-b4f8587c-503c-45ce-af34-6d4223a0933d.png)

Dungeon Quests don't show up on the map... we've always shown them at the dungeon entrance location(s). Would be good to follow that convention I think.

![image](https://user-images.githubusercontent.com/55365231/194733341-ba0c450b-7ed0-4e5e-8334-6594165745e8.png)

And when you are inside a dungeon with a map, they don't show up in the right place on the map.

Better to NOT show them on maps in dungeons I think. It's just confusing since not all dungeons have maps, and we don't have coordinates in maps for the quests items / quest givers.

![image](https://user-images.githubusercontent.com/55365231/194733352-4c9189ae-5864-402b-b432-e15e48999c87.png)

**Comment by BreakBB** [comment]
The Wotlk Dungeons are the first to have maps with real coordinates. Because of that our database also contains spawn information for NPCs/objects inside of them. BUT that got in our way with the "mark the dungeon entry as objective location". I'll see to add these spawn information back to those NPCs, so we also show the objectives on the dungeon entry again.

**Comment by Gogo1951** [comment]
Better not to list something, than list the wrong location. Would be easy to turn the map icons off for instance maps. 

Closing as stale. Will never get worked on.
