### ISSUE TITLE
The Spire of Blood shouldn't visiable

### ISSUE THREAD

**Issue by Firehex12** [Questie/Questie#4413]
## Description

On your map you can see yellow mark of quest starter for quest https://www.wowhead.com/wotlk/quest=11654/the-spire-of-blood
I came to point found npc, but he didn't give any quest. Problem is - you will be able to start this quest only from quest item, which drops from patroling mob https://www.wowhead.com/wotlk/npc=26115/darkfallen-bloodbearer So you should place his route on map instead

## Questie & WoW version
7.3.3, Wrath classic

**Comment by BreakBB** [comment]
Hey @Firehex12 not sure what the problem is on this quest.

The icon is showing and so is the patrol path 🤔 

![grafik](https://user-images.githubusercontent.com/33514570/195979238-a1786da7-1b85-49d9-8aed-767d075bf137.png)

**Comment by Yttrium-tYcLief** [comment]
I think the confusion here is the fact that the beginning of the path of the mob that drops the starting item actually overlaps the eventual end recipient of this quest. In reality, it's just some confusing data, but we're representing the data correctly. If you hover over the ! you should be able to see the fact that this quest starts from the mob, rather than the NPC:
![image](https://user-images.githubusercontent.com/1037011/198148178-86ba2ea8-3ab3-4b04-ab74-3874573a4ee8.png)
