### ISSUE TITLE
(5781) Of Forgotten Memories [wrong loc]

### ISSUE THREAD

**Issue by brian8544** [Questie/Questie#4420]
## Description

Quest bag marker is wrong, it must be set on 24.8, 79.8

## Wowhead link
]
(https://www.wowhead.com/wotlk/quest=5781)

## Screenshots

(https://youtu.be/Cw3q-Z9WUFM?t=19)

**Comment by Yttrium-tYcLief** [comment]
This one is a regression from Classic because of the fact that the map for Eastern Plaguelands changed with the addition of Acherus in WotLK. All coordinates have shifted, and the correction for this one was absent from our database. You can notice that the coordinates are wrong on Wowhead as well.

I've issued a commit with your provided coordinates that should fix it.

**Comment by brian8544** [comment]
> 

Awesome, thanks for your time & commit, I'd put a PR myself in, but I have no idea how to even start in such enormous project. Let alone follow the standardized code. 

/Closing issue.

**Comment by Yttrium-tYcLief** [comment]
For the record, you didn't have to close the issue - it was going to be closed automatically by GitHub when the fix was merged to master.
