### ISSUE TITLE
Questie Needs a "Suggested Repair" Tool

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4630]
So you're already popping up some text saying something like, "We don't have this quest in the DB!"

How hard would it be to just add that to a log file, and build in the surrounding instructions for people to create PRs?

If you pick up a quest you aren't expecting to find on an NPC (or can't pick up a Quest you're expecting to find at that NPC), or complete an escort quest at the revised Wrath location (vs. the legacy Vanilla locations), or find some loot on a mob you didn't think had that loot on it... all these seem like easy things to log, and build into a little file that had instructions with how to patch Questie, or how to send the log to your Discord server.

If you had this, then people could just play the game and generate a massive list of fixes, and kick it over whenever they wanted. 

I doubt it'd be too too much effort, certainly less effort than trying to fix all the BS that's wrong with Quest data still. And there are a LOT of things wrong. I know you guys don't play much, but every zone has I'd estimate 5-25 problematic quests still. The northrend zones, and any of the zones updated for wrath are hardest hit. Additionally, there's a TON of quests that you're missing due to racial requirements or breadcrumbs that shouldn't show up if you do the followup first.

Step one, building a logging tool...

Step two, building a "PR Suggestion" tool based on the logs. I'd keep them as two separate files.

This would help show more people how easy it is to send PRs too, and help you guys to recruit some new blood.

@BreakBB

**Comment by Muehe** [comment]
Well in related news, I recently added raw data display to the search (when debug mode is enabled in advanced settings) to the search feature, which should at least make debugging a bit more accessible:

![pic related](https://cdn.discordapp.com/attachments/810171186000298044/1067664933761843301/Screenshot_20230125_053732.png)

Could be better, but who has the time...

Anyway regarding making PRs more accessible with some (semi-)automated solution, I'd prefer this and a proper guide on the wiki over an elaborate solution like wowhead has, not least because currently dumping a WTF file on Github would expose a lot of data about usage, so it's a privacy concern; But also because correcting quest data is not *that* hard, it's essentially modifying one of four text file on the correct expansion. I'll admit it's not well explained anywhere, which we should remedy.

I'll say though I think you underestimate how much time and knowledge about Questie internals (for which the experts are partly gone) it would take to implement this. First off, the whole compiled DB in byte code is saved right next to all the settings, and all the Journey history for individual characters, which makes it next to impossible to copy anything out of there manually with most editors. This could be scripted around, or we could make an ingame window that provides the suggested correction to copy and past, but neither of those are trivial to implement.

**Comment by Gogo1951** [comment]
Start with something small.

When you interact with an NPC, check to see if you have coordinates for that NPC.. and check to see if you're "sorta close" to the coordinates you have in the DB. If not... easy...

`````
==========
NPC Fixes
==========

You have data that Questie doesn't have! Please help improve Questie by going to https://github.com/Questie/Questie/blob/master/Database/Corrections/wotlkNPCFixes.lua and pasting in this code.

        [19481] = {
            [npcKeys.spawns] = {[zoneIDs.NETHERSTORM]={{58.34,86.4}}},
        }, 
`````

Do the same things for quests...

Note, you may not get a perfect fix until a person finishes questing... right, it may just grab the quest starts by NPC, but it won't know where it ends until you turn it in. That's fine. It can slowly capture data across thousands of users and over time you'll have better data.

This wouldn't be terribly hard... you already output an error, just change the error to also report in a log file.

`````
==========
Quest Fixes
==========

You have data that Questie doesn't have! Please help improve Questie by going to https://github.com/Questie/Questie/blob/master/Database/Corrections/wotlkQuestFixes.lua and pasting in this code.

        [12946] = {
            [questKeys.startedBy] = {nil,{400019}},
        },
`````

Do the same for objects...

`````
==========
Object Fixes
==========

You have data that Questie doesn't have! Please help improve Questie by going to https://github.com/Questie/Questie/blob/master/Database/Corrections/wotlkObjectFixes.luaand pasting in this code.

        [193092] = {
            [objectKeys.spawns] = {[zoneIDs.ICECROWN] = {{36.6,67.6}}},
        },
`````

Would that fix everything? No... it wouldn't fix issues around race requirements, or profession requirements, but it would help with some glaring issues. Then you'd have more free time to fix some of the nuanced issues. AND... but helping empower users to see how easy it is to start in on fixes, you'll end up with more users making fixes.

As for privacy 🙄 ... man, there's no personal information at stake. It's just game log data. Caring about who can see if you did a quest or not... that's some real next-level tin-foil hat shit.

It would be nice to see you "Core" guys take improving Questie a bit more seriously. It's really shit still. It's gotten a bit better since launch, but it's still really buggy. I know none of you play any more, but a lot of people still do play and it's impossible to just blow through a zone like we could in Vanilla, or even TBC, without having to stop and alt-tab and look shit up because Questie is bugged.

400+ open issues... most of those are still data issues. Hope the plan isn't to just let them all rot.

**Comment by Muehe** [comment]
> Start with something small.

I did, I sent a screenshot of it...

> When you interact with an NPC, check to see if you have coordinates for that NPC.. and check to see if you're "sorta close" to the coordinates you have in the DB.

As usual, you underestimate the task. First off we only get player coordinates from the API, not NPC coordinates, plus checking for proximity isn't really *that* trivial either. You might have to find the nearest spawn out of a list of 50, mobs might have been kited away from their spawn location, you have to define "sorta close", maybe add some leeway. It gets complex fast.

> Please help improve Questie by going to https://github.com/Questie/Questie/blob/master/Database/Corrections/wotlkNPCFixes.lua and pasting in this code.

Correct me if I'm wrong, but I don't think you can paste anything directly into files on Github unless you have push rights and click the edit button. Plus the fix might need to go into the TBC or Classic file depending on when the NPC was added.

> just change the error to also report in a log file.

In which "log file"? The one where the compiled DB is saved and which is thus unreadable in most editors?

> AND... but helping empower users to see how easy it is to start in on fixes, you'll end up with more users making fixes.

Yeah, nice idea. My problem is that implementing it, as per usual with many of your suggestions, would take a lot more effort than you think. A wiki page still comes out better in my personal cost-benefit-analysis.

> As for privacy :roll_eyes: ... man, there's no personal information at stake. It's just game log data. Caring about who can see if you did a quest or not... that's some real next-level tin-foil hat shit.

You do you, I'm sitting in Europe and I won't be opening that GDPR can of worms because you roll your eyes at me, thank you very much.

> It would be nice to see you "Core" guys take improving Questie a bit more seriously. It's really shit still. It's gotten a bit better since launch, but it's still really buggy. I know none of you play any more, [...] 400+ open issues... most of those are still data issues. Hope the plan isn't to just let them all rot.

Yeah you got us, that's our plan. Letting the project rot. /s And you don't even see the irony of wasting our time with stupid flame wars like this when there are 400+ issues open...

If you want to fact-check your accusations then take a look at the commit log, or at the Insights page, and you might realise **more** effort has gone into WotLK than into the other two versions. As I keep telling you, the base data was just way more incomplete than it was for Classic/TBC.

And seriously, check your attitude. Don't get me wrong, I appreciate you still reporting stuff and making suggestions; But if you don't stop it with the passive aggressive abuse I will at some point ask Aero to ban you on here. Enough is enough.

**Comment by Gogo1951** [comment]
Cool. Just say what it is, you won't work on anything I suggested. 

I don't underestimate work so much as you don't want to do ANY work.

You'd rather just waste everyone's time with a long email about it.

What a joke. Citing GDPR for WoW Character data?

GDPR... there's no PII here, it's a video game character. What a bullshit excuse.

No wonder Quesite is in the state it's in.

Closing this as stale, it'll never get worked on.

**Comment by Gogo1951** [comment]
Also, @Muehe ... @AeroScripts knows what I do for a day job.

I can safely say that there's no GDPR issues here.

Just want to put that to bed. What a joke of an excuse.
