### ISSUE TITLE
Lua error on trying to get player position using proximity sort option

### ISSUE THREAD

**Issue by haarenas** [Questie/Questie#4802]
## Bug description
This error appeared 2 times today:
1- When I was taking the ship from Theramore Isle to Menethil Harbor and as soon as the loading screen ended the error showed up
2- When using heartstone from Iron Forge to Argent Tournament

It seems it try to get my position before I load into the map. This only ocurred when Im already logged in and encounter a loading screen (when opening wow for the first time the error does not appear)

Im using the option to **sort quest by proximity**

```
Message: Usage: local position = C_Map.GetPlayerMapPosition(uiMapID, unitToken)
Time: Mon Apr 24 20:37:20 2023
Count: 1
Stack: Usage: local position = C_Map.GetPlayerMapPosition(uiMapID, unitToken)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `GetPlayerMapPosition'
[string "@Interface/AddOns/Questie/Modules/Tracker/TrackerUtils.lua"]:478: in function <...face/AddOns/Questie/Modules/Tracker/TrackerUtils.lua:475>
[string "@Interface/AddOns/Questie/Modules/Tracker/TrackerUtils.lua"]:740: in function <...face/AddOns/Questie/Modules/Tracker/TrackerUtils.lua:734>
```

I have a question related to the [last changes to that file](https://github.com/Questie/Questie/commit/a8334918ea5a99c609e6cfba23232842fe0d5371#diff-00e4f91fb380ef63223ce4f53527819b3f866a608f19ec689cf0b01cd89719f8R740), why is necessary the "if state" from line 735 if in line 729 verifies that is not in an instance?

## Questie & WoW version
Questie V8.0.1
WoW version wotlk classsic v3.4.1.48632

**Comment by BreakBB** [comment]
Hey @haarenas thanks for reporting this, we will look into it!

**Comment by BreakBB** [comment]
> I have a question related to the [last changes to that file](https://github.com/Questie/Questie/commit/a8334918ea5a99c609e6cfba23232842fe0d5371#diff-00e4f91fb380ef63223ce4f53527819b3f866a608f19ec689cf0b01cd89719f8R740), why is necessary the "if state" from line 735 if in line 729 verifies that is not in an instance?

This verifies that the `C_Timer.NewTicker` in line 734 is only started when the is not in an instance.

https://github.com/Questie/Questie/blob/a8334918ea5a99c609e6cfba23232842fe0d5371/Modules/Tracker/TrackerUtils.lua#L729

This check is inside the ticker to stop it once the player enters an instance.

https://github.com/Questie/Questie/blob/a8334918ea5a99c609e6cfba23232842fe0d5371/Modules/Tracker/TrackerUtils.lua#L735

**Comment by Dyaxler** [comment]
This is a weird one! Why all of a sudden are we having issues with the Proximity sort feature? This has been part of Questie since day 1 of Classic WoW almost 4 years ago? The only thing I did recently is a refactor and it was moved into the TrackerUtils.

And technically, when on a ship or using a hearth stone it's basically the same code as zoning into an instance. Except you're "zoning" to another map in the world.

I'm wondering if there has been some serious "back end" updates server side that is causing some lag during these events. I might have to rethink this entire stack and make it impervious to timing issues.

Clearly more testing is needed. I'll put this on my To-Do list. At least it's not a "show stopper".
