### ISSUE TITLE
Bug with some quests not showing up in Tracker

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4804]
[[8] The Ravaged Caravan (751)] - check this one out? It should have some objective. It used to show on the map... I'm 99% sure.

![image](https://user-images.githubusercontent.com/55365231/234202543-c13d5f82-391b-49b6-a900-72f0023d3995.png)

No marks where the turn in should be.

![image](https://user-images.githubusercontent.com/55365231/234202712-f85e3ee3-46a8-4f40-9892-e1c1933c49cf.png)

**Comment by BreakBB** [comment]
I _think_ this is a Questie data VS API issue. As you can already see on wowhead the wotlk version has an "Explore zone" objective, which the classic version does not.

https://www.wowhead.com/wotlk/quest=751/the-ravaged-caravan
vs.
https://www.wowhead.com/classic/quest=751/the-ravaged-caravan

And from what I know there actually is not "Explore Zone" objective, but you just need to return to the NPC. That also explains both issues: First you don't see a correct objective in the Tracker because there is not a real one and since the quest is not complete you don't see the turn in icon.

**Comment by Dyaxler** [comment]
@Gogo1951 so you're playing in Classic Exclusively? Just wondering because some of your other bugs have me scratching my head. In the future, please tell us which expansion you're using. ;)

I think I can build in a "check" to display "completion/description" text in place of a missing objective. I'll put it on my to-do list.

**Comment by BreakBB** [comment]
This bug should be on Wotlk @Dyaxler not Classic Era

**Comment by Dyaxler** [comment]
Then his quest would show "Explore Zone" as an Objective whereas on the Classic version, that line is blank.

**Comment by Gogo1951** [comment]
I play Wrath Classic mostly.

**Comment by Dyaxler** [comment]
> I play Wrath Classic mostly.

Okie... so the screen shot is from which expansion? I need to know where to being looking at why this happens. And... roll a horde cow and repro it locally so I can see what the returns on the DB are. :D

**Comment by Dyaxler** [comment]
Just for the sake of being thorough... made sure the quest appears correctly in WotLK.
![image](https://user-images.githubusercontent.com/17400948/235007075-b3ddb5fc-4447-4f7a-9336-ea1f601e518c.png)

**Comment by Dyaxler** [comment]
Hmm... works fine in Classic too. Maybe we fixed this issue since release...

![image](https://user-images.githubusercontent.com/17400948/235031764-50f1b3a4-5cf6-4518-a3a0-7ee898fba75a.png)

**Comment by Dyaxler** [comment]
Oh, and even the Quest Finisher is present.

![image](https://user-images.githubusercontent.com/17400948/235031995-1d5a74b0-6f3e-425e-815d-1515c4696db4.png)

**Comment by Gogo1951** [comment]
I'm not seeing the same thing on a Blood Elf Warlock. Odd.

**Comment by Dyaxler** [comment]
We've been doing a ton of bug squashing so it's entirely possible that I have the "fixed bits" in my local build. :D

**Comment by BreakBB** [comment]
Closing this for the upcoming release. Feel free to report back if you encounter this issue again!
