### ISSUE TITLE
questie tracker not working

### ISSUE THREAD

**Issue by fastasheet** [Questie/Questie#4807]
## Bug description

Recently my questie has had everything working besides the tracker, the tracker works for a little bit and then it doesn't update when I turn in or accept new quests then I reload my ui and then the tracker is completely gone. I've tried to do everything for the recommended fixes, any help would be appreciated.

## Screenshots

servers are down otherwise I would submit one 

## Questie & WoW version

Classic Era

**Comment by fastasheet** [comment]
![image](https://user-images.githubusercontent.com/131784041/234398686-7e08a961-7770-4ded-b7df-ad2c90b45c32.png)
 here is a screenshot of my screen

**Comment by fastasheet** [comment]
also my questie version is 8.0.1

**Comment by MyTechnoHunter** [comment]
What happens if you /questie then goto tracker tab to make sure its enabled?

**Comment by fastasheet** [comment]
It is enabled and I reset and nothing happens even when I disable and re enable it nothing happens

**Comment by fastasheet** [comment]
even re downloading the addon does nothing

**Comment by MyTechnoHunter** [comment]
Screenshot your questie options,  gen tab and tracker tab

Might join the Discord to get faster responses

**Comment by fastasheet** [comment]
![image](https://user-images.githubusercontent.com/131784041/234405334-b4ba32aa-84f3-491a-bb84-ddbaba2e74f3.png)

**Comment by fastasheet** [comment]
![image](https://user-images.githubusercontent.com/131784041/234405416-e14a724e-8880-4e53-ab59-7b883b5927b5.png)

**Comment by fastasheet** [comment]
![image](https://user-images.githubusercontent.com/131784041/234405488-39cfa416-a46a-48d1-b20a-103c3452624c.png)

**Comment by fastasheet** [comment]
![image](https://user-images.githubusercontent.com/131784041/234405594-6ccafee7-608a-4605-a54f-d8ecd4254682.png)

**Comment by fastasheet** [comment]
I tried to join the discord earlier but  I Don't have nitro and it just kept taking me to the classic server discord which didn't seem like the right one.

**Comment by MyTechnoHunter** [comment]
https://discord.gg/TTUHSu7q

**Comment by MyTechnoHunter** [comment]
You hit reset, and the enable/disable?

**Comment by fastasheet** [comment]
yes

**Comment by fastasheet** [comment]
I just did it again and it is working atm but I'm not sure if it will last is there anything I can do to make sure it doesn't do this in the future?

**Comment by Dyaxler** [comment]
I have a sneaky feeling that this is due to the fact that we moved the Tracker Enabled option from the Global profile to the per Character profile and your migration was either interrupted or not executed properly. Not sure why. I just reviewed the code, and it looks fine. If my theory is in fact correct for your case, then I think it might be an edge case / one off. *Crosses Fingers* I say that because if it is this then a LOT more people would have run into this issue. So, I "think" you're ok.

Did it only happen to one character or other alts?

**Comment by fastasheet** [comment]
one character specifically doesn't work at all and the rest work most of the time but stop track sometimes

**Comment by fastasheet** [comment]
and sometimes if I relog and reset it it works but other times it doesn't

**Comment by Dyaxler** [comment]
@fastasheet I've been thinking about this for the past couple of days. One of our team members experienced a similar issue where in game settings weren't being saved to his SavedVariables so each time he logged in or reloadUI his settings would revert. Not sure why it happened except that sometimes those files can get corrupted. I'd rather you not delete your Questie SavedVariables file because you'd lose all your Journal data.

Does the issue happen if you create a new character?

**Comment by CramerBH** [comment]
I too am having this issue. Specifically Im encountering it while doing the tournament dailies. Normally when I would complete the kill 10 of x mob the icons on the map and minimap should go away and the tracker on screen should update. Neither occur. Eventually after either a load screen or a reload ui the tracker updates but the icons on map never seem to keep up and go away when they ought to. started occuring about an hour or two ago, wasnt happening prior to then, last update was yesterday I think so it isnt a direct before and after from that I believe.

**Comment by Dyaxler** [comment]
Try the new update folks. There was a perf issue we discovered this morning pertaining to Map Icons that was causing some lag. Duplicate icons too I think. The code responsible has been present since v8 so awhile now. We think it might have caused some other update type issues as well. At least it is our hope that this morning's patch fixes these.
