### ISSUE TITLE
After a longer session, auto-turn-in & auto-quest-accept stop working

### ISSUE THREAD

**Issue by Gogo1951** [Questie/Questie#4857]
In Wrath.

This bug is similar to the bug we had back in Vanilla, where after a long session things just sort of stopped working.

After you quest for an hour or so, all of a sudden the auto-turn-in doesn't work for any quest until you do a reload. 

I just assumed it was an issue on my side and with the taint issues in the past it was hard to be sure, but after my questing buddy in Discord reported it... I started looking more closely. 

From a clean session start, we both hit the issue at different times, but by 1-2 hours into the session we had both experienced auto-turn-in / auto-quest-accept stop working. I also saw this when questing solo.

No Lua errors or taint reported.

**Comment by Gogo1951** [comment]
We were both running Elv, Details, DBM, Weak Auras... other than that I don't know, but I know he's not a big add-on guy.

**Comment by Dyaxler** [comment]
There were some performance issues we caught this morning, caused by me... MY BAD! :D It's been corrected in the newest version...

I know this is in relation to Auto-Quest but the performance issues introduced by my mistake could lead to timing issues for back end updates and certain functions might not fire in the right order. At least I hope our fix for my mistake will solve this.
