### ISSUE TITLE
add a fake tracker frame to help with using the percentage of screen slider in tracker options

### ISSUE THREAD

**Issue by MyTechnoHunter** [Questie/Questie#4860]
## Description
should we have a "fake" tracker that shows when manipulating the percentage slider while options is open? People are not getting the settings right i think.. confusion and locked heights..
If your quest list isn't full you don't see it grow as it stops at the bottom of your current list

**Comment by Dyaxler** [comment]
Clarification… not a “Fake” tracker but more like a “Pre-View” of what the Trackers height would be if it were fully loaded with Quests. That way you’ll know exactly how high it’ll grow and where it’ll be on your screen so that when it is full, it’ll already be in the desired location. 

Great idea!

**Comment by Starlynk1** [comment]
Please add this since the tracker does not resize any larger than what quests you have during resize. This is very frustrating.
