### ISSUE TITLE
Some objectives wrap to 2nd line, others append with '...' - how to force the former?

### ISSUE THREAD

**Issue by sushileaf** [Questie/Questie#4905]
**Hey there!** 

I was just curious, as I have been for a long time with Questie, how come some objectives will wrap into a 2nd line if the text is long... but other objectives will append with '...' instead?

I would love if all long objectives would just wrap to a 2nd line if they go beyond the width of the tracker. 

Is there a way to force this always? Clearly this functionality is possible, since it does happen in some cases.

It would be absolutely 1000% perfect if all objectives could just fully show within the constraints of whatever tracker width I set. 

If this is possible already, and I've overlooked it, it would be great to know how <3.

Much love, and thank you for an awesome addon, as always!

**Example screenshot**: [SHOWN HERE](https://i.imgur.com/yeJorp8.png)

**Comment by Dyaxler** [comment]
This might help: https://github.com/Questie/Questie/pull/4886#issuecomment-1544809632

It's a little blurb I wrote about the Trackers "Sizer" tab. In your case, just "Right Click" it and it'll put the tracker back in Auto mode. The next release will have a helpful tooltip. If you're already in manual mode, dragging the Tracker wider will get rid of the truncation dots (...)

**Comment by Dyaxler** [comment]
@sushileaf 

I've just finished merging a PR that has a ton of fixes in it... hopefully the new feature for the Tracker Sizer will help.

https://github.com/Questie/Questie/commit/61a23348902328c0f4977954b1d226031ba6f378

and

https://github.com/Questie/Questie/commit/2ca38d31b1fc27daf1915e6eed82cd128c86a31d

...hopefully a new version will get pushed out soon. Keep an eye out.

**Comment by sushileaf** [comment]
@Dyaxler 

In manual mode, which is what I was using for that screenshot, it doesn't get rid of the dots for every objective only some, which is my first issue. 

But if I try the right click thing, which does indeed put it in auto mode, this ends up where the width also becomes very wide on long objectives. 

Is there a compromised mode? I'd love the height to be automatic, but the width to stay tight and small. If I keep it manual mode, the new quests will extend into that cut off scrollable area (or I can manually continue to resize it each time I pick up a quest). 

When the auto is on for wide objectives, the tracker becomes pushed out into the more central part of the screen. 

Do you get what I mean? 

I just want it to stay thin, but auto fill to the bottom of the screen when needed, and show full objective text.

**Comment by Dyaxler** [comment]
@sushileaf 

We just released a new version. Please give it a shot and let me know. There were some "formatting" errors that have been corrected. Not trying to ignore your other questions but based on your screen shot that line should have been wrapped. I'd like to get that part resolved at the very least.

General rule of thumb for how the wrapping works. 

Only Objectives are wrapped if Blizzard Completion Text returns true. For example, the three Quests you referenced in your screen shot. Also, these types of objectives aren't limited to 2 lines. They can wrap beyond that depending on Tracker width. Manual and Auto mode.

Objectives with a "Graphical Representation" like Objectives that require you to collect Money. So far, the only ones I've seen are Achievements. These types are "split" into two lines... technically not wrapped. The "split" point will always be the point at which the text ends and the Money graphic begins. I have no idea why Blizzard doesn't do this will all Objective types like Reputation for example. In Auto mode the longest line is used to measure how wide the tracker needs to be. In manual mode, if the Trackers boundary comes close to the end of the label... the label will get truncated, and you'll see the (...) on the end. If you manually size the tracker and both the text label and the Graphic fits on one line, then the line "split" goes away, and it becomes one line.

Why don't we wrap objectives with a number criteria? There are actually two types of number criteria quests. Ones with a single objective and those with multiple objectives. Multiple objectives are never wrapped. It would make it too difficult at certain Tracker widths to determine, at a glance, which number criteria tab went with an objective because it would get wrapped into a second line, or even a third in some cases. It turns the Tracker into a spaghetti nest which made it hard to read. For single objectives with a number criteria, at one point I was wrapping those and trimming off the [0/1] / [1/1] tags and relying on the objective color to show the player the objective was complete. There is one color profile that doesn't color the objective based on how complete it was, so I added check marks. (White Profile). Players LOVED the check marks, but everyone still wanted the number criteria tags... even for quests with a single number criteria.

**Comment by sushileaf** [comment]
Woops I meant to come back to this. 

@Dyaxler Thank you very much for all the insight.

The new version of Questie is perfection. The resizing is beautiful now, and works exactly how I need it to work.

It's crazy odds because I've had issues with the resizing for what feels like a couple years lol, and right after I come mention it, you smash it with the update <3.

Thank you for all the hard work.
