### ISSUE TITLE
Tracker integration for VoiceOver

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#4921]
## Description

The addon [VoiceOver](https://github.com/mrthinger/wow-voiceover) allows the user to "play" the quest text for nearly every quest. It would be great to have this Play-button also in the Tracker or maybe as a right click option.

The Play Button in the quest log:
![grafik](https://github.com/Questie/Questie/assets/33514570/a93c92f5-e929-4e4b-af39-67b4a53d2eb7)

**Comment by Dyaxler** [comment]
Here is an idea... focus your attention on the "Min/Max" buttons. If this addon is loaded and while the Quest is in a Maximized state... if a Player Holds their Shift Key down... the "Minimize" button would change to a Play Button and they can play the VoiceOver. This could also work for Quest Item Buttons too. We could make those disappear too and replace it with a Play Button while the Shift Key is down.

Does this addon cover Achievements too? 

![image](https://github.com/Questie/Questie/assets/17400948/72a7805c-9315-4faf-bbc3-0b6dd350f722)

**Comment by BreakBB** [comment]
I like that idea @Dyaxler !

**Comment by Dyaxler** [comment]
I think I'm about finished! I went a little further than just adding simple Play Buttons.

- Play Buttons on the Tracker update when a Quest is being played/stopped with VoiceOver.

- Play Buttons will show (will hide the Quest Item Buttons and Min/Max Buttons) whenever the Shift Key is pressed while hovering OVER the Tracker Frame.

- Play Buttons will hide whenever the Shift Key is released no matter where the mouse pointer is. Quest Item Buttons and Min/Max Buttons will return to their appropriate visible state based on options and mouse location.

- If the Tracker is minimized while a Quest is being played with VoiceOver, the VoiceOverFrame will hide, and the VoiceOver sound queue will empty. Same thing happens if you suddenly untrack all your Quests.

- The VoiceOverFrame while visible (appears when a Quest is being played), will be attached to the Tracker depending on a players' desired Tracker Grows setting. In the screenshot below I'm using "Up & Right", so the NPC frame is attached to the upper right corner.

- Canceling a playing or queued Quest from the NPC frame will update the Play Buttons in the Tracker.

- The Play Buttons availability states will turn Grey/Fade for any audio file not in the VoiceOver DB.

![image](https://github.com/Questie/Questie/assets/17400948/81d546da-4704-49a6-85ff-e9a1738c63b1)

**Comment by MyTechnoHunter** [comment]
Nifty

**Comment by BreakBB** [comment]
Any branch/PR to test this @Dyaxler ?

**Comment by Dyaxler** [comment]
Nil errors nuked. Code works in both Wrath and Classic. I just wish they would hurry up and add BC and Wrath quests. :D
