### ISSUE TITLE
Missing XP value in map tooltip near "Active"

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#4951]
If you press Shift while mousover a quest icon on map or minimap you get extra info that is very useful. However the quest that is on row with the "Active" description is not being shown that XP value. The value exists in DB.

![image](https://github.com/Questie/Questie/assets/1155017/244745c1-210f-4bdf-89bb-a1497ebac2f0)

8.4.2

**Comment by MyTechnoHunter** [comment]
To clarify,  the above pic is a mouseover pic of map/minimap pin? Where does active come from?

**Comment by BreakBB** [comment]
The „Active“ means that you hover over an objective, not an accept/complete icon.

This should be easy to fix.

**Comment by Cabro** [comment]
Everything that is below "Active" are quests in your quest log. This one is from map

**Comment by BreakBB** [comment]
Oh right, I didn’t look close enough.

Well then it should be a simple data issue 🤔

**Comment by MyTechnoHunter** [comment]
so you hovered what on the map? the quest symbol by the dungeon entrance?

**Comment by Cabro** [comment]
it's for any quest icon tooltip from questie on map/minimap when you press shift

**Comment by MyTechnoHunter** [comment]
and it shows all quests in one tooltip? it doesnt just give more info on the quest that icon represents?

i am confused.. wth are you actually hovering over to see a tooltip.. what shows when not shifted.. i recall seeing icons that  were quest givers.. it shows the quests they give, hitting shift gave details of those quests.. not that unholy mess of a pic you have
i refuse to believe ALL of those re at one giver?

**Comment by Cabro** [comment]
there are many quest givers where i mouseover. i will record and post on disc

**Comment by Dyaxler** [comment]
@Cabro 

According to the code comments... it looks like this is by design.

![image](https://github.com/Questie/Questie/assets/17400948/04e3e8bf-a169-4b65-aede-a590a2e6f8fc)

The map/minimap icon tooltips work much the same way the Clustering Code works. Not only does it consolidate the icons, but it also consolidates nearby tooltips from other Icons. Whenever you see an `(Active)` tag in a tooltip, doesn't matter if you're hovering over an NPC, Available Quest Icon, or Completed Quest Icon; it's actually in fact an objective that is currently in your Questl Log.

My pointer is hovering over the Completed Quest Icon...

![image](https://github.com/Questie/Questie/assets/17400948/99e0f939-f687-4ea2-a9f0-ec886f44a593)

As @BreakBB stated... this can be an easy change. If that is what everyone wants... I can check this into my PR today.

![image](https://github.com/Questie/Questie/assets/17400948/f9bc970e-7eb1-44e9-8b69-b65768282363)

**Comment by MyTechnoHunter** [comment]
Looks good to me

**Comment by Cabro** [comment]
Yes, looks good to me too!
