### ISSUE TITLE
When i leave combati get this

### ISSUE THREAD

**Issue by thiartc** [Questie/Questie#5018]
Wow Classic - WOTLK

Questie version - 8.8.1 (updated 3 July 2023)

Message: ...rface/AddOns/Questie/Modules/QuestieEventHandler.lua:479: attempt to index global 'QuestieConfigFrame' (a nil value)
Time: Tue Jul  4 15:01:42 2023
Count: 1
Stack: ...rface/AddOns/Questie/Modules/QuestieEventHandler.lua:479: attempt to index global 'QuestieConfigFrame' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/Questie/Modules/QuestieEventHandler.lua"]:479: in function <...rface/AddOns/Questie/Modules/QuestieEventHandler.lua:468>
[string "=[C]"]: ?
[string "@Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...las/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/Atlas/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by BreakBB** [comment]
Can you disable the `Atlas`addon and try again @thiartc ?

**Comment by thiartc** [comment]
i did, tried all on the list

**Comment by thiartc** [comment]
no atlas

Message: ...rface/AddOns/Questie/Modules/QuestieEventHandler.lua:479: attempt to index global 'QuestieConfigFrame' (a nil value)
Time: Tue Jul  4 15:50:54 2023
Count: 1
Stack: ...rface/AddOns/Questie/Modules/QuestieEventHandler.lua:479: attempt to index global 'QuestieConfigFrame' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/Questie/Modules/QuestieEventHandler.lua"]:479: in function <...rface/AddOns/Questie/Modules/QuestieEventHandler.lua:468>
[string "=[C]"]: ?
[string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/AtlasLootClassic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: (*temporary) = <function> defined =[C]:-1

**Comment by thiartc** [comment]
seems to be with elvui

**Comment by BreakBB** [comment]
So when you disable ElvUI no errors? @thiartc 

Try to run just Questie to verify it is not Questie itself.

**Comment by thiartc** [comment]
will do, but it worked perfectly with all m addons till most current update

so something that was updated within questie is messing all others

if i just disable questie i get no errors

**Comment by Muehe** [comment]
@thiartc There is a slight misunderstanding here:

> so something that was updated within questie is messing all others

> if i just disable questie i get no errors

> if i want to use questie, i have to disable all addons on that list

It could be that our new (or old) code errors because some other addon is loading an outdated version of Ace3. If the only active addon is Questie and the error does not happen then that is a very strong possibility.

If that is the case you can find out which addon causes the error by re-abling them (or batches of them) one by one until the error happes again. Replacing that addons Ace copy with a newer one might fix the error entirely: https://www.curseforge.com/wow/addons/ace3/files/4040413

Alternatively you can wait for the next release or download Dyaxlers commit [from here](https://github.com/Questie/Questie/archive/ebac6388a4c24b0eaa37ef797c619b80edfd081e.zip) to see if that helps. Word of warning, the commit download contains approximately 100 MB of files you won't need.

Please let us know what you find out. :pray:
