### ISSUE TITLE
Durability frame gets removed by Questie.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#5022]
Probably moved off screen or something and not put back.

https://discord.com/channels/263036731165638656/810171186000298044/1126615035557449779

Wotlk 8.8.1

**Comment by Dyaxler** [comment]
Fixed in: https://github.com/Questie/Questie/pull/5013

**Comment by Dyaxler** [comment]
Updated PR:

- Mirrored the functions code and logic for consistency.

- While using the "Sticky" options, both the Durability Doll and Voiceover Sound Queue frames will be attached to the Tracker while quests are tracked, and the Tracker is in a maximized state (Only while visible and determined by the API's visibility states). Otherwise, if the Tracker is minimized or there are no quests being tracked then both of these frames will be "reset" to their default locations.

- While NOT using the "Sticky" options both the Durability Doll and Voiceover Sound Queue frames will be left alone. Or, upon disabling either option, they will be reset back to their default positions individually.
