### ISSUE TITLE
Questie needs a way to detect quest status for quests without objectives.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#5032]
They can turn from complete to incomplete when you delete the sourceitemid item, and Questie fails to detect this.

8.8.1

**Comment by Dyaxler** [comment]
The test case I used was [18] The Price of Shoes (118) where upon acceptance, Verner's Note (1283) is given to the player and the Quest is immediately flagged as Complete. This quest has no objective data in Questies' DB and no objective data is returned by any Blizzard API's because... the quest is immediately complete. All you have to do is bring Verner's Note to the quest finisher. Previously, if for some strange reason the player decides to destroy Verner's Note... then the quest still shows up as being complete. I.E. Bug!

Now, Questie will tell you which item you're missing and properly show the quest incomplete in the Tracker.

**Comment by Cabro** [comment]
Fix confirmed
