### ISSUE TITLE
Unchecking "show pfquest icons" force enables "always glow behind map icons".

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#5039]
8.8.2

**Comment by Dyaxler** [comment]
This is by design... 

When toggling pfQuest Icon style ON there are specific "default" settings that it requires so some of the settings are changed. When toggling it OFF and going back to the Questie Icon style, we MUST return all the settings back to Questies default settings, which includes "Always Glow Behind Map Icons" which is enabled by default in Questie.

**Comment by Cabro** [comment]
Sounds like bad design if it forces settings on you. Can you just not touch the map icons glow setting?

**Comment by Muehe** [comment]
If you don't want other settings to change along you can click the button below and change the icons manually. The option was just added in preparation of a style selection window shown on first login and will eventually be removed completely.
