### ISSUE TITLE
Objectives of failed quests are redrawn on reload

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#5044]
## Bug description

When you fail on a quest and then `/reload` the objective icon is drawn and not the accept icon. When you initially fail the quest the objective is hidden correctly and the accept icon is drawn though.

Tracker is showing everything correctly.

## Screenshots

![grafik](https://github.com/Questie/Questie/assets/33514570/05a15cb4-2775-4055-9ee5-e6b1a896aafa)

## Questie & WoW version

v8.8.2

**Comment by Cabro** [comment]
Eh, how did i miss this one. Bug confirmed.

**Comment by Dyaxler** [comment]
There is a comment in the code from the person who originally wrote this module inside the `QuestieQuest:GetAllQuestIds()` function:

```
--This prevents us from adding Failed Quests to the tracker - we want the ability to track all quests.
--elseif data.isComplete ~= -1 then -- TODO FIX LATER. Now currentQuestLog may have part of failed quests. Check what is needed? All or none of those?
```

While in game when a quest is updated it runs `QuestieQuest:UpdateQuest(questId)`. This function has had its logic significantly improved over the last several months. This is why in game quest updates are perfectly fine.

When you either login or do a reloadUI it scans the players quest log and does a very rudimentary update by running ONLY `QuestieQuest:GetAllQuestIds()`. This has so far worked out quite well for the most part, however I knew it would only be a matter of time before someone else saw this bug too. I've had my eye on it for quite some time and have been meaning to circle back around to it. Not entirely sure what the code comment is referring to specifically, but we'd want to update and show ALL quests... even failed ones.

I can add a quick check to GetAllQuestIds() to run UpdateQuest() for failed questIDs only... but I'm starting to think that maybe we should just run UpdateQuest() for each questID that GetAllQuestIds() iterates through since the logic is now pretty solid.

**Comment by Dyaxler** [comment]
By the way... this isn't an actual tooltip issue. It's more or less a "Quest State" issue. When you first login it does the basic stuff. When a quest is in a failed state, there are some additional "clean up" routines that need to fire to bring the quest state back to a more or less "Available" state...

**Comment by Dyaxler** [comment]
@BreakBB did you want me to make the code changes I outlined above? Or did you have something else in mind?

**Comment by Dyaxler** [comment]
@BreakBB opps... I was playing with this yesterday and left in some modified code in this commit:

https://github.com/Questie/Questie/pull/5043/commits/83163d502a78e9a0298a9f51e8f88d2c3eb4657a

![image](https://github.com/Questie/Questie/assets/17400948/c9c2eb5f-24f2-4bf3-96d1-e7607469ac8c)

Soooo, technically this is fixed? But this would only handle failed quests upon login or reloadUI. It would fix your bug but it doesn't really address the underlying logic. I really don't think it would hurt to expand the scope and just run QuestieQuest:UpdateQuest(questId) for each questId iterated by QuestieQuest:GetAllQuestIds(). Unless there is some logic bomb I'm not considering here...

**Comment by BreakBB** [comment]
Oh, so the bug I reported was only on your PR not on master? 🤔

Then I guess you can close this issue and simply create a new one for the other bug/TODO.

**Comment by Cabro** [comment]
It was present for me, too
