### ISSUE TITLE
Creature special objective tooltips are lost when changing continents.

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#5053]
After a continent change:
![image](https://github.com/Questie/Questie/assets/1155017/72ff21a4-89e1-4608-a75e-e15c73386032)

A /reload fixes them:
![image](https://github.com/Questie/Questie/assets/1155017/f6c7e396-015c-4157-abd5-dfd1f7ebbe42)

8.8.2 wotlk Dyaxler PR

**Comment by Dyaxler** [comment]
The source of this bug was in QuestieQuest:SmoothReset(). It was clearing all the Tooltip tables without clearing the `objective.hasRegisteredTooltips` and `objective.registeredItemTooltips` keys. Created `QuestieQuest:ClearAllToolTips()` to handle that behavior properly.

Additional bug that is somewhat related:

We have a method (`_AddSourceItemObjective(quest)`) for adding a Special Objective Item Tooltip derived from the `quest.sourceItemId` DB Key but not items contained in the `quest.requiredSourceItems` DB Key. A new method (`_AddRequiredSourceItemObjective(quest)`) has been added and like AddSourceItemObjective - it checks the quests objectives indexes to make sure the item is not already referenced and also checks the `quest.sourceItemId` key and will skip these ID's to prevent any duplicate Tooltips from being generated.

I've also gone back through and refactored a number of QuestieQuest functions to take advantage of our new and improved QuestieTooltips:RemoveQuest(questId) method.

Note: Special Objective Item Tooltip's are "special" objectives and there is really no way of knowing how many "items" are needed to finish a quest. Sometimes these counts are referenced in the quests description but often times there isn't any clue at all. There is no Blizzard API we can leverage to get this number. So, if you see an item in the tooltip with a `1/1 'Item Name'` and it's green, then it's an item derived by the `quest.sourceItemId` DB Key and these item references mean you only need one of them. For these items specifically, you'll see a 0/1 or 1/1 tag and will be colored based on your Objective Color profile preference. Items without a "Number Criteria Tag" are tooltips derived from the `quest.requiredSourceItems` DB Key and will sometimes require X number in order to complete. For example, https://www.wowhead.com/wotlk/item=42246/essence-of-ice for the quest: https://www.wowhead.com/wotlk/quest=12981/hot-and-cold. Again, these items will not have a number critera. There will always be one line present, and it will remain grey no matter how many you gather.

**Comment by Dyaxler** [comment]
This bug fix will also add a tooltip to Draconic for Dummies drops - another example:
![image](https://github.com/Questie/Questie/assets/17400948/4117c868-0978-450e-9a48-8e9247a69068)
