### ISSUE TITLE
Lua error when loading

### ISSUE THREAD

**Issue by Masoleno** [Questie/Questie#5058]
I get the following LUA error when first logging in and also when clicking on quests in the quest log.
Message: ...ce/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1817: attempt to perform arithmetic on a nil value
Time: Fri Aug  4 18:47:50 2023
Count: 1
Stack: ...ce/AddOns/Questie/Modules/Tracker/QuestieTracker.lua:1817: attempt to perform arithmetic on a nil value
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:1817: in function `UpdateHeight'
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:1742: in function `UpdateFormatting'
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:1651: in function `Update'
[string "@Interface/AddOns/Questie/Modules/Tracker/QuestieTracker.lua"]:1692: in function `func'
[string "@Interface/AddOns/Questie/Modules/Libs/QuestieCombatQueue.lua"]:25: in function <...e/AddOns/Questie/Modules/Libs/QuestieCombatQueue.lua:17>

Locals: (*temporary) = <function> defined =[C]:-1

I am using Questie version 8.8.3 in WoTLK Classic (v. 3.4.2.50664).

The error occurs even if all other addons are disabled.

**Comment by Dyaxler** [comment]
@Masoleno 

Huh... were you in combat? 

Is this the first time you've upgraded to a new version in a while?

Line 1817:
`trackerQuestFrame.ScrollChildFrame:SetHeight((TrackerLinePool.GetFirstLine():GetTop() - trackerLinePool.GetCurrentLine():GetBottom() + 3))`

`trackerQuestFrame` and the `ScrollChildFrame` are both initialized before the Tracker module. It's entirely possible that these frames could be nil upon login if you were in combat, but that test case has been pounded. My guess is a race condition. If it's a "one off" error, then I wouldn't really worry about it. reloadUI and move on. :) If it keeps happening each time you login, then it might be some weird race condition or another addon is conflicting. Might have to look into adding a nil check on that frame but it's not really necessary because these two frames should never be nil.

**Comment by BreakBB** [comment]
Closing this as it is very outdated and no response was given.
