### ISSUE TITLE
Wrong Mouseover on Quest WANTED: Chok'sul

### ISSUE THREAD

**Issue by scheumell** [Questie/Questie#5163]

**Comment by scheumell** [comment]
The sign in Thelsamar(Loch Modan), which gives the quest WANTED: Chok'sul (link: https://classic.wowhead.com/quest=256 ), shows the quest WANTED: Baron Longshore from the Barrens when you hover over it with your mouse.
Game: Wow Classic
Questie Version: v8.10.6

**Comment by scheumell** [comment]
![grafik](https://github.com/Questie/Questie/assets/147829216/b4ee0419-f6b6-47d0-9d5c-883744bdb73c)

**Comment by MyTechnoHunter** [comment]
Known issue, wanted boards all have the same id so questie, as is, has no way to tell which it is

**Comment by BreakBB** [comment]
> Known issue, wanted boards all have the same id so questie, as is, has no way to tell which it is

This is not entirely true. There is no API to get an _ID_ from an object in the world, so Questie has to look for an object in the database by the _name_ of the object. And since these signs are all named "WANTED" Questie finds a couple of objects.

A user on Discord suggested to limit the findings based on the current zone of the player, which I find quite clever. Still this is a niche issue as most wanted quests have different level ranges 🙈
