### ISSUE TITLE
Class/Profession based quests show name in english

### ISSUE THREAD

**Issue by anon1231823** [Questie/Questie#5358]
## Bug description
The quests for classes and professions in the tracker show the name in english, not localized.

## Screenshots
![image](https://github.com/Questie/Questie/assets/67269448/d0047824-2299-491b-85a2-e46b6a057dad)

**Comment by Cabro** [comment]
The category?

**Comment by anon1231823** [comment]
I have seen it under Blacksmithing, Herbalism, Paladin, Priest, Druid. I assume all the rest too

**Comment by BreakBB** [comment]
We have the `lookupZones` which are used to find the header for each quest.

From a short look it seems like this is totally outdated since it is only used for `zoneOrSort` entries for which the game API returns nothing. Most likely only the special negative values. And the return value of that is not translated, so the Tracker only shows the values of `lookupZones`.

We do have the translations though, so the fix should be easy.
