### ISSUE TITLE
Breadcrumb Quest "Blackwatch" showing as available

### ISSUE THREAD

**Issue by Davyd2400** [Questie/Questie#5367]
I have opened a ticket about this before, and the issue had been fixed as of the previous update to Questie, but as of the most recent update the issue has cropped up again (and then some). The breadcrumb quest "Blackwatch" from Baron Sliver in Icecrown is shown as available on the map, even though it is not (Blackwatch has already been unlocked, quest giver is not offering this quest). 

Another unavailable breadcrumb quest has appeared on my map as well which was never there before, "The Earthen of Ulduar", from Brann Bronzebeard. This is another example of a breadcrumb that is not available to me but shown as available on the map.

**Comment by Cabro** [comment]
I just did Blackwatch in the last days. It's all sorts of weird, it's not a breadcrumb, i could take Blackwatch while having the next quest in quest log. Adjusted the exclusivity, though. If you did the quest chain it shouldn't be shown.

"The Earthen of Ulduar" simply showed up because i gave a spawn location to an NPC which didnt have one until now. It should also be fixed, i found it to have inversed exclusivity to its followup. 

Take these fixes, let me know if it fixes those quests for you (i can't test horde quests) - https://github.com/Questie/Questie/commit/0d3e9aad3720088475bd70be63f0fe2bebfd50f5
