### ISSUE TITLE
Wrong reputation for many quests

### ISSUE THREAD

**Issue by BreakBB** [Questie/Questie#5384]
## Description

As stated [here](https://github.com/Questie/Questie/pull/5381#issuecomment-1872174369) there are quite a few vanilla quests where reputation reward is incorrect. Either the quest grants reputation for another faction or the value is wrong or both.

We might be able to use the scraper to fetch these values.

## Questie & WoW version

v9.2.11

**Comment by danez** [comment]
Where is the current quest db sourced from?
I'm happy to look at this. Is [this](https://github.com/Questie/Questie/tree/master/ExternalScripts(DONOTINCLUDEINRELEASE)/scraper) the scraper u are talking about?

**Comment by BreakBB** [comment]
Iirc the reputation was orginally from cmangos, just like almost every other data.

@Muehe and @Logonz should know more about that.

Also: Yes, that is the scraper. Currently it is only used for the new SoD quests.

**Comment by danez** [comment]
I got the scraper up and running, and it was really easy to get all the data for reputation from wowhead. Just took a while to run :)

Now what would be the best way to get this data into questie? Should I create overwrites for all these quests that are wrong, which might be a lot?

I was wondering if it might make sense to start a separate database, which can be updated from wowhead. Otherwise right now there might be data in the extension code that is not even used, because it is instantly overwritten by the corrections. So that makes the addon bigger and potentially also faster...unless there is some compilling/compressing involved for the lua files that I haven't seen.

I've also seen some of the quests in the questdb do not exist on wowhead, but need to check what they are exactly.

So I just want to make sure how I should proceed here.

:)

**Comment by BreakBB** [comment]
That sounds great!

About size and performance of the DB: Don't worry @Logonz is working on a complete rewrite which will improve performance by a ton!

For now I think the easiest way to get the data in fast, but also leave it open to update it, is to create a new correction file which contains only the reputation fixes. That will work around the fact that we already have a ton of corrections for every expansion 😅

The format of the file should be the same as for regular quest corrections and you can search for `_LoadCorrections` on the code to see how the new file should be handled. Also make sure to add it to the appropriate TOC files.

Maybe @Muehe and @Yttrium-tYcLief also want to chime in on this.
