### ISSUE TITLE
Shaman Class Rune Quest (Stalk with the Earthmother) Part 2 - quest ID 76160 

### ISSUE THREAD

**Issue by LetaRogers** [Questie/Questie#5466]
Questie v9.2.14

Classic Season of Discovery

Reference on Wowhead:
https://www.wowhead.com/classic/quest=76160/stalk-with-the-earthmother

This is Part 2 in a series of quests for a shaman rune.  Part 1 (76156) involved a dangerous blowing up of wagons inside the Venture Co. mine in Mulgore, which shows as [11] difficulty (IIRC).

For Part 2, the issues are:

1) The waypoint locations of the Windfury cones that you are to gather are not shown on the map. They are located in the same area that you do this quest:

https://www.wowhead.com/classic/quest=744/preparation-for-ceremony

2) When you mouseover the cones on the ground, they should show you how many you have collected so far;

3) The quest difficulty is shown as level [6] and is gray. It should be the same as part 2 of this quest chain (where you go in the Venture Co. mine and blow up wagons) or the same difficulty as the "Preparation for Ceremony" quest (where you pull the tails off dead harpies). I suggest difficulty [11]

**Comment by LetaRogers** [comment]
![image](https://github.com/Questie/Questie/assets/768345/6717ec81-a5d6-443e-b72c-6bc36c2f9c38)

**Comment by BreakBB** [comment]
Hey @LetaRogers 

Thanks for reporting this issue. About the changes you request:

> 1. The waypoint locations of the Windfury cones that you are to gather are not shown on the map. 

Absolutely, I just did a fix which will be included in the next release. It's great you also brought up the "Preparation for Ceremony" quest, that helped a lot.

> 2. When you mouseover the cones on the ground, they should show you how many you have collected so far;

This is a general limitation of Questie. For the quest you need to collect [Pine Salve](https://www.wowhead.com/classic/item=206175/pine-salve) so that is what will get counted.

> 3. The quest difficulty is shown as level [6] and is gray.

This is correct. As your screenshot shows, Blizzard also marks this as gray quest (so level 6 most likely). Questie always follows this, to be as accurate as possible.
