### ISSUE TITLE
Disconnects: IsDoable could use some performance improvements

### ISSUE THREAD

**Issue by Kalaww** [Questie/Questie#5947]
## Bug description
Since Cata Classic prepatch, Questie disconnect me when I pick up a quest or hand in a quest. It happen very often but not on every quest.
I can reproduce the disconnection easily with questie as the only addon loaded and on any character.

## Screenshots
Screenshot just before the disconnection
![image](https://github.com/Questie/Questie/assets/5639270/1e27e435-6daf-41bb-b378-ef506ec2a4c7)

Here the video with profiler+logs https://streamable.com/04655i

## Questie & WoW version
Questie v10.0.7
Cataclysm Classic 4.4.0

**Comment by BreakBB** [comment]
Hey @Kalaww 

Thanks for bringing this up. There are certainly improvements we can make, even though they didn't have any high prio, because "it works".

On a range from "potato" to "high performance gaming PC", where would you place your machine?

Because this looks a lot different on my machine:

<img width="1414" alt="image" src="https://github.com/Questie/Questie/assets/33514570/77eac1fb-eb4a-445b-bff7-39bcc61e0115">
(This is with trivial quests enabled, which increases the load)

Also even if the "call count" is high, your "time"s are pretty low as well 🤔

**Comment by Kalaww** [comment]
Thanks for checking. I would say my machine is high performance (amd 5800X and rtx 4080). I didn't saw anyone else reporting this here or on discord so I guess it's coming from my setup.

**Comment by Kalaww** [comment]
Well I just did a fresh install of questie (with saved variables deleted) and it looks like the issue isn't there anymore. Sorry for the unnecessary noise and thanks for this amazing addon!

**Comment by BreakBB** [comment]
No worries @Kalaww 

I'll still keep this open, to chime in minor improvements, which won't hurt.

**Comment by BreakBB** [comment]
@Cheykan about this:

> the reason why i "blame" questie is no disconnects after disabling it.

Try to disable all addons _except_ Questie and see if that still causes issues.

Disconnects usually happen, when addons (a single one or the combination of multiple), is causing very high load and slowing down the WoW client too much. So maybe it's not Questie, but either a different addon or the combination of them.

**Comment by Cheykan** [comment]
> @Cheykan about this:
> 
> > the reason why i "blame" questie is no disconnects after disabling it.
> 
> Try to disable all addons _except_ Questie and see if that still causes issues.
> 
> Disconnects usually happen, when addons (a single one or the combination of multiple), is causing very high load and slowing down the WoW client too much. So maybe it's not Questie, but either a different addon or the combination of them.

Thanks for reply. My pc is somehwere between a potato and a toaster and i wouldn't rule out that my pc is the issue but i disabled all addons and went thru them one by one, i don't use that many. Questie is the only one causing this problem. Deleted WTF and Cache folder since that usually fix most issues. Uninstalled questie, deleted variables without luck, also tried erlier versions.

**Comment by BreakBB** [comment]
So even with just Questie active, you experience disconnects? Can you link the disconnects to some ingame activity? Like quest accept as OP stated?

**Comment by Cheykan** [comment]
seems to work just fine now.

**Comment by italankin** [comment]
I experience disconnects mostly when I hovering over NPCs when turning in quests (my spec is Ryzen 9 7900X and RTX 4090). Questie is the one causing these disconnects, disabling it solves the issue completely.

Here is profiler data for approx 5 min of gameplay with turning in 2 quests and 13 total in quest log:

![image](https://github.com/Questie/Questie/assets/1196012/130617d1-9fd3-4aa6-8bc9-53b42aa51365)

I tried to clear cache and WTF folder but had no luck.

**Comment by BreakBB** [comment]
Hey @italankin 
About this:
> Questie is the one causing these disconnects, disabling it solves the issue completely.

Did you also test with just Questie active?

**Comment by italankin** [comment]
> Did you also test with just Questie active?

Yes, with only Questie enabled disconnects are also happening.

**Comment by Cheykan** [comment]
i disabled auto accept/turn in, haven't had a DC since.

**Comment by BreakBB** [comment]
The next release will bring in some improvements on this topic. Would be great if you could then report back if your issues persist.

**Comment by italankin** [comment]
> i disabled auto accept/turn in, haven't had a DC i 2 days now, i forgot too post it until now.

I have these options turned off.

**Comment by BreakBB** [comment]
Hey @Kalaww @italankin and @Cheykan - If you didn't do it yet, please update to Questie v10.0.9 and see if that helps with your issue

**Comment by italankin** [comment]
I do not see any improvements in v10.0.9 compared to v10.0.8. However, on 13 May (still using v10.0.8) I started to see much less disconnects - and mostly when I turn in multiple quests or cancel them (usually happens after a ~1s delay after completion/cancellation).

Haven't tried v10.0.9 with only Questie enabled, I will test it later and report the result.

**Comment by BreakBB** [comment]
v10.0.8 brought in the first improvements, directly towards disconnects. v10.0.9 brought improvements about the performance of `IsLevelRequirementsFulfilled`

**Comment by Cheykan** [comment]
my corseforge is always up and on autoupdate on addons i use, since i turned off automation of quests in questie and uses leatrix plus for quest autos i haven't had any dc's connected to quest handling. Questie is like ElvUI, i won't play the game unless i have these 2 addons.. i/we are spoiled rotten haha

**Comment by BreakBB** [comment]
@Kalaww @Cheykan @italankin 

The following Questie version contains the _potential fix_ for your disconnects. It would be great to get your feedback, because I still wasn't able to reproduce the issue.

[Questie-v10.0.10-b5d3a5e36.zip](https://github.com/Questie/Questie/files/15330239/Questie-v10.0.10-b5d3a5e36.zip)

⚠️ This version is for Cataclysm only!

We found that with certain settings (e.g. **not** showing PvP quests on the map) Questie might hammer the API on Blizzards side a bit too hard, causing the disconnect. This only recently became a problem, because Blizzard drastically increased the throttling of their API, so addons need to adjust to that.

If you need assistance to manually install an addon feel free to ask or read [the installation guide](https://github.com/Questie/Questie/wiki/Installation-Guide).

**Comment by italankin** [comment]
Tried latest release from CurseForge (v10.0.10), started to experience disconnects when crafting (shortly after crafting an item). Happens only when Questie enabled, enabling/disabling other addons has no effect.

Do you use English client? I am playing the Russian one, maybe this is the case? (I also tried to set English in the Questie settings, no luck)

**Comment by BreakBB** [comment]
@italankin I am playing on an English client in the EU, but I don't think this is linked. Did you try the version I posted above to see if that helps? Note that it is not the `v10.0.10` from CurseForge more a `v10.0.11-beta`.

**Comment by italankin** [comment]
Tried `Questie-v10.0.10-b5d3a5e36` version, and it seems like the situation has significantly improved. Haven't seen any disconnects since the update.

**Comment by BreakBB** [comment]
Thanks for testing and reporting back @italankin !

We'll ship a proper release with the fix at some point today.
