### ISSUE TITLE
Why isn't Shagu, the creator of pfQuest, credited?

### ISSUE THREAD

**Issue by HerrTiSo** [Questie/Questie#6672]
### Description

As Questie is obviously heavily inspired by Shagu's pfQuest, even naming a setting(s) after it, I feel you guys should definitely properly credit him for his work.

**Comment by BreakBB** [comment]
I personally joined the Questie team with the Classic announcement, so I can't tell what exactly inspired the OG creators.

After taking another look at pfQuest I do see the similarities though and there are places in the code which already credit Shagu/pfQuest.

Interesting is that Questie originally was built for 1.12 WoW, so it was a rivial to pfQuest.

I am calling in @Muehe and @Logonz for this, as they are around since the start.

**Comment by Muehe** [comment]
@HerrTiSo As BreakBB said both pfQuest and Questie are similar to other addons that existed before. Specifically, Questie for 1.12  was based on QuestHelper, and pfQuests predecessor, ShaguQuest, was based on WHDB.

Both pfQuest and Questie for 1.13 and above are entirely rewritten from scratch though.

The only thing we are using directly from pfQuest are icons (which is why that setting is named after it), and we do so [with permisson](https://github.com/Questie/Questie/issues/4659#issuecomment-1428433280) and [with attribution](https://github.com/Questie/Questie/blob/master/Icons/LICENSE.md).

If @shagu thinks we should give more credit than that I am certainly willing to do so, but haven't heard anything about him being unsatisfied with how we do it now.

So until I hear otherwise I am going to close this issue (feel free to ask more questions though if you have any, IIRC you should be able to post on closed issues).

**Comment by shagu** [comment]
This was probably just a misunderstanding. 

> If @shagu thinks we should give more credit than that I am certainly willing to do so, but haven't heard anything about him being unsatisfied with how we do it now.

I'm totally fine with the credit you gave me for the icons. Everything good :)

> The initial commit of pfQuest was October 2017

pfQuest was a rewrite of my previous project "ShaguQuest" (which itself was a fork of WHDB in the beginning). That one was uploaded to github in version 3.2 in March 2015. 

ShaguQuest has started slightly more than a year before Questie started to develop. We've been in contact since the beginning and I even got asked if I'd like to join before it even started. 

As @Muehe already pointed out, we had different goals: ShaguQuest/pfQuest always had more focus to be like WHDB/MobMap  and Questies original plan was to backport QuestHelper.
