### ISSUE TITLE
Questie - Out of date

### ISSUE THREAD

**Issue by dagid4** [Questie/Questie#6685]
### Description

I have downloaded the last version of Questie v10.9.2. For now it is only 4 days old, but it says Out of date on Classic Era WoW 1.15.5.57638. Is this normal behavior?

![Snímek obrazovky 2024-11-20 165322](https://github.com/user-attachments/assets/710b97c1-cd4e-4527-8183-14322a17bc77)

### Questie version

v10.9.2

### Game flavor

Era/HC

**Comment by BreakBB** [comment]
The "Out of date" just means that Questie (and other addons) has not been updated for WoW patch v1.15.5 (which is only out since today/yesterday). In most cases you can just activate "Load out of date addons" and everything will work as expected. For this patch that is true for Questie.

This has been fixed in 23a3edd and will be released in a few hours.

For now activate the setting said above and update as soon as the next Questie version is available.

**Comment by dagid4** [comment]
Thank you for explanation
