### ISSUE TITLE
Debug output

### ISSUE THREAD

**Issue by GregoryGH** [Questie/Questie#6705]
### Description

debug output in chat on some random events like ah or mail
Nothing to update. cacheMiss, doRetryWithoutChanges false false

### Questie version

Questie v10.10.0-b1, Client 1.15.5 SoD, Locale enUS

### Game flavor

Season of Discovery

**Comment by BreakBB** [comment]
Hey @GregoryGH 

Yeah we noticed, thanks for reporting this! Thankfully it only affects the latest beta version.

We'll release a stable version soon, removing this print 👍🏻 

Side note:
It's not fired at "random events", but every time Questie needs to check for quest log changes. Thanks to Blizzard Questie even needs to check after bank or mail closing, because the API does not fire any quest log event 🤦🏻

**Comment by BreakBB** [comment]
Fixed in e4115de05a8a694ff18d297996c4bac9cea0a0b7
