### ISSUE TITLE
Wrong mob level for Look To The Stars [181]

### ISSUE THREAD

**Issue by gabbsmo** [Questie/Questie#6776]
### Description

The quest item drops from a level 30 mob, not 32 as it says in Questie shows in the shift key tooltip on the map. See https://www.wowhead.com/classic/quest=181/look-to-the-stars

### Questie version

v10.11.0

### Game flavor

Era/HC/Anniversary

**Comment by Cabro** [comment]
Thank you for your report. NPC levels have been changed a lot throughout vanilla, and as such the NPC level won't be accurate 100% based on each phase. I changed the level of this NPC either way.
Keep up the good job!

Fixed in https://github.com/Questie/Questie/commit/18828ff2970bbd236a0890752294ed6e7a9aa77d
