### ISSUE TITLE
SOD_HIDE corrections are propagated into Cataclysm

### ISSUE THREAD

**Issue by Cabro** [Questie/Questie#6802]
### Description

`tinsert(eventQuests, {"Winter Veil", 8769, "25/12", "2/1", QuestieCorrections.SOD_HIDE}) -- A Ticking Present`

This blacklists the quest in Cataclysm. Could be because of holiday quest corrections, too

### Questie version

10.11.2

### Game flavor

Cata

**Comment by BreakBB** [comment]
This is the part causing the trouble:

https://github.com/Questie/Questie/blob/master/Database/Corrections/Holidays/QuestieEvent.lua#L136-L139

This was not updated since WotLK as it seems and as soon as anything is in the 5th field of the entry, the quest will only be shown when `Questie.IsClassic` is true (which is only the case of Era/HC/Anniversary).
